// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/alipayorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AlipayOrderUpdate is the builder for updating AlipayOrder entities.
type AlipayOrderUpdate struct {
	config
	hooks    []Hook
	mutation *AlipayOrderMutation
}

// Where appends a list predicates to the AlipayOrderUpdate builder.
func (_u *AlipayOrderUpdate) Where(ps ...predicate.AlipayOrder) *AlipayOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *AlipayOrderUpdate) SetOrderNo(v string) *AlipayOrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *AlipayOrderUpdate) SetNillableOrderNo(v *string) *AlipayOrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AlipayOrderUpdate) SetUserID(v int64) *AlipayOrderUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AlipayOrderUpdate) SetNillableUserID(v *int64) *AlipayOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AlipayOrderUpdate) AddUserID(v int64) *AlipayOrderUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *AlipayOrderUpdate) SetPackageID(v int) *AlipayOrderUpdate {
	_u.mutation.ResetPackageID()
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *AlipayOrderUpdate) SetNillablePackageID(v *int) *AlipayOrderUpdate {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// AddPackageID adds value to the "package_id" field.
func (_u *AlipayOrderUpdate) AddPackageID(v int) *AlipayOrderUpdate {
	_u.mutation.AddPackageID(v)
	return _u
}

// SetCnyFee sets the "cny_fee" field.
func (_u *AlipayOrderUpdate) SetCnyFee(v int) *AlipayOrderUpdate {
	_u.mutation.ResetCnyFee()
	_u.mutation.SetCnyFee(v)
	return _u
}

// SetNillableCnyFee sets the "cny_fee" field if the given value is not nil.
func (_u *AlipayOrderUpdate) SetNillableCnyFee(v *int) *AlipayOrderUpdate {
	if v != nil {
		_u.SetCnyFee(*v)
	}
	return _u
}

// AddCnyFee adds value to the "cny_fee" field.
func (_u *AlipayOrderUpdate) AddCnyFee(v int) *AlipayOrderUpdate {
	_u.mutation.AddCnyFee(v)
	return _u
}

// SetUsdAmount sets the "usd_amount" field.
func (_u *AlipayOrderUpdate) SetUsdAmount(v float64) *AlipayOrderUpdate {
	_u.mutation.ResetUsdAmount()
	_u.mutation.SetUsdAmount(v)
	return _u
}

// SetNillableUsdAmount sets the "usd_amount" field if the given value is not nil.
func (_u *AlipayOrderUpdate) SetNillableUsdAmount(v *float64) *AlipayOrderUpdate {
	if v != nil {
		_u.SetUsdAmount(*v)
	}
	return _u
}

// AddUsdAmount adds value to the "usd_amount" field.
func (_u *AlipayOrderUpdate) AddUsdAmount(v float64) *AlipayOrderUpdate {
	_u.mutation.AddUsdAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AlipayOrderUpdate) SetStatus(v string) *AlipayOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AlipayOrderUpdate) SetNillableStatus(v *string) *AlipayOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (_u *AlipayOrderUpdate) SetAlipayTradeNo(v string) *AlipayOrderUpdate {
	_u.mutation.SetAlipayTradeNo(v)
	return _u
}

// SetNillableAlipayTradeNo sets the "alipay_trade_no" field if the given value is not nil.
func (_u *AlipayOrderUpdate) SetNillableAlipayTradeNo(v *string) *AlipayOrderUpdate {
	if v != nil {
		_u.SetAlipayTradeNo(*v)
	}
	return _u
}

// ClearAlipayTradeNo clears the value of the "alipay_trade_no" field.
func (_u *AlipayOrderUpdate) ClearAlipayTradeNo() *AlipayOrderUpdate {
	_u.mutation.ClearAlipayTradeNo()
	return _u
}

// SetQrCode sets the "qr_code" field.
func (_u *AlipayOrderUpdate) SetQrCode(v string) *AlipayOrderUpdate {
	_u.mutation.SetQrCode(v)
	return _u
}

// SetNillableQrCode sets the "qr_code" field if the given value is not nil.
func (_u *AlipayOrderUpdate) SetNillableQrCode(v *string) *AlipayOrderUpdate {
	if v != nil {
		_u.SetQrCode(*v)
	}
	return _u
}

// ClearQrCode clears the value of the "qr_code" field.
func (_u *AlipayOrderUpdate) ClearQrCode() *AlipayOrderUpdate {
	_u.mutation.ClearQrCode()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AlipayOrderUpdate) SetExpiresAt(v time.Time) *AlipayOrderUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AlipayOrderUpdate) SetNillableExpiresAt(v *time.Time) *AlipayOrderUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *AlipayOrderUpdate) SetPaidAt(v time.Time) *AlipayOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *AlipayOrderUpdate) SetNillablePaidAt(v *time.Time) *AlipayOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *AlipayOrderUpdate) ClearPaidAt() *AlipayOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetNotifyData sets the "notify_data" field.
func (_u *AlipayOrderUpdate) SetNotifyData(v string) *AlipayOrderUpdate {
	_u.mutation.SetNotifyData(v)
	return _u
}

// SetNillableNotifyData sets the "notify_data" field if the given value is not nil.
func (_u *AlipayOrderUpdate) SetNillableNotifyData(v *string) *AlipayOrderUpdate {
	if v != nil {
		_u.SetNotifyData(*v)
	}
	return _u
}

// ClearNotifyData clears the value of the "notify_data" field.
func (_u *AlipayOrderUpdate) ClearNotifyData() *AlipayOrderUpdate {
	_u.mutation.ClearNotifyData()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AlipayOrderUpdate) SetUpdatedAt(v time.Time) *AlipayOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AlipayOrderMutation object of the builder.
func (_u *AlipayOrderUpdate) Mutation() *AlipayOrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AlipayOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlipayOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AlipayOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlipayOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AlipayOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := alipayorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AlipayOrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := alipayorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "AlipayOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := alipayorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AlipayOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AlipayTradeNo(); ok {
		if err := alipayorder.AlipayTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "alipay_trade_no", err: fmt.Errorf(`ent: validator failed for field "AlipayOrder.alipay_trade_no": %w`, err)}
		}
	}
	return nil
}

func (_u *AlipayOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(alipayorder.Table, alipayorder.Columns, sqlgraph.NewFieldSpec(alipayorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(alipayorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(alipayorder.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(alipayorder.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(alipayorder.FieldPackageID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPackageID(); ok {
		_spec.AddField(alipayorder.FieldPackageID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CnyFee(); ok {
		_spec.SetField(alipayorder.FieldCnyFee, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCnyFee(); ok {
		_spec.AddField(alipayorder.FieldCnyFee, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsdAmount(); ok {
		_spec.SetField(alipayorder.FieldUsdAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsdAmount(); ok {
		_spec.AddField(alipayorder.FieldUsdAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(alipayorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AlipayTradeNo(); ok {
		_spec.SetField(alipayorder.FieldAlipayTradeNo, field.TypeString, value)
	}
	if _u.mutation.AlipayTradeNoCleared() {
		_spec.ClearField(alipayorder.FieldAlipayTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.QrCode(); ok {
		_spec.SetField(alipayorder.FieldQrCode, field.TypeString, value)
	}
	if _u.mutation.QrCodeCleared() {
		_spec.ClearField(alipayorder.FieldQrCode, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(alipayorder.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(alipayorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(alipayorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NotifyData(); ok {
		_spec.SetField(alipayorder.FieldNotifyData, field.TypeString, value)
	}
	if _u.mutation.NotifyDataCleared() {
		_spec.ClearField(alipayorder.FieldNotifyData, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(alipayorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alipayorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AlipayOrderUpdateOne is the builder for updating a single AlipayOrder entity.
type AlipayOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AlipayOrderMutation
}

// SetOrderNo sets the "order_no" field.
func (_u *AlipayOrderUpdateOne) SetOrderNo(v string) *AlipayOrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *AlipayOrderUpdateOne) SetNillableOrderNo(v *string) *AlipayOrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AlipayOrderUpdateOne) SetUserID(v int64) *AlipayOrderUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AlipayOrderUpdateOne) SetNillableUserID(v *int64) *AlipayOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AlipayOrderUpdateOne) AddUserID(v int64) *AlipayOrderUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *AlipayOrderUpdateOne) SetPackageID(v int) *AlipayOrderUpdateOne {
	_u.mutation.ResetPackageID()
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *AlipayOrderUpdateOne) SetNillablePackageID(v *int) *AlipayOrderUpdateOne {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// AddPackageID adds value to the "package_id" field.
func (_u *AlipayOrderUpdateOne) AddPackageID(v int) *AlipayOrderUpdateOne {
	_u.mutation.AddPackageID(v)
	return _u
}

// SetCnyFee sets the "cny_fee" field.
func (_u *AlipayOrderUpdateOne) SetCnyFee(v int) *AlipayOrderUpdateOne {
	_u.mutation.ResetCnyFee()
	_u.mutation.SetCnyFee(v)
	return _u
}

// SetNillableCnyFee sets the "cny_fee" field if the given value is not nil.
func (_u *AlipayOrderUpdateOne) SetNillableCnyFee(v *int) *AlipayOrderUpdateOne {
	if v != nil {
		_u.SetCnyFee(*v)
	}
	return _u
}

// AddCnyFee adds value to the "cny_fee" field.
func (_u *AlipayOrderUpdateOne) AddCnyFee(v int) *AlipayOrderUpdateOne {
	_u.mutation.AddCnyFee(v)
	return _u
}

// SetUsdAmount sets the "usd_amount" field.
func (_u *AlipayOrderUpdateOne) SetUsdAmount(v float64) *AlipayOrderUpdateOne {
	_u.mutation.ResetUsdAmount()
	_u.mutation.SetUsdAmount(v)
	return _u
}

// SetNillableUsdAmount sets the "usd_amount" field if the given value is not nil.
func (_u *AlipayOrderUpdateOne) SetNillableUsdAmount(v *float64) *AlipayOrderUpdateOne {
	if v != nil {
		_u.SetUsdAmount(*v)
	}
	return _u
}

// AddUsdAmount adds value to the "usd_amount" field.
func (_u *AlipayOrderUpdateOne) AddUsdAmount(v float64) *AlipayOrderUpdateOne {
	_u.mutation.AddUsdAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AlipayOrderUpdateOne) SetStatus(v string) *AlipayOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AlipayOrderUpdateOne) SetNillableStatus(v *string) *AlipayOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (_u *AlipayOrderUpdateOne) SetAlipayTradeNo(v string) *AlipayOrderUpdateOne {
	_u.mutation.SetAlipayTradeNo(v)
	return _u
}

// SetNillableAlipayTradeNo sets the "alipay_trade_no" field if the given value is not nil.
func (_u *AlipayOrderUpdateOne) SetNillableAlipayTradeNo(v *string) *AlipayOrderUpdateOne {
	if v != nil {
		_u.SetAlipayTradeNo(*v)
	}
	return _u
}

// ClearAlipayTradeNo clears the value of the "alipay_trade_no" field.
func (_u *AlipayOrderUpdateOne) ClearAlipayTradeNo() *AlipayOrderUpdateOne {
	_u.mutation.ClearAlipayTradeNo()
	return _u
}

// SetQrCode sets the "qr_code" field.
func (_u *AlipayOrderUpdateOne) SetQrCode(v string) *AlipayOrderUpdateOne {
	_u.mutation.SetQrCode(v)
	return _u
}

// SetNillableQrCode sets the "qr_code" field if the given value is not nil.
func (_u *AlipayOrderUpdateOne) SetNillableQrCode(v *string) *AlipayOrderUpdateOne {
	if v != nil {
		_u.SetQrCode(*v)
	}
	return _u
}

// ClearQrCode clears the value of the "qr_code" field.
func (_u *AlipayOrderUpdateOne) ClearQrCode() *AlipayOrderUpdateOne {
	_u.mutation.ClearQrCode()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AlipayOrderUpdateOne) SetExpiresAt(v time.Time) *AlipayOrderUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AlipayOrderUpdateOne) SetNillableExpiresAt(v *time.Time) *AlipayOrderUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *AlipayOrderUpdateOne) SetPaidAt(v time.Time) *AlipayOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *AlipayOrderUpdateOne) SetNillablePaidAt(v *time.Time) *AlipayOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *AlipayOrderUpdateOne) ClearPaidAt() *AlipayOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetNotifyData sets the "notify_data" field.
func (_u *AlipayOrderUpdateOne) SetNotifyData(v string) *AlipayOrderUpdateOne {
	_u.mutation.SetNotifyData(v)
	return _u
}

// SetNillableNotifyData sets the "notify_data" field if the given value is not nil.
func (_u *AlipayOrderUpdateOne) SetNillableNotifyData(v *string) *AlipayOrderUpdateOne {
	if v != nil {
		_u.SetNotifyData(*v)
	}
	return _u
}

// ClearNotifyData clears the value of the "notify_data" field.
func (_u *AlipayOrderUpdateOne) ClearNotifyData() *AlipayOrderUpdateOne {
	_u.mutation.ClearNotifyData()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AlipayOrderUpdateOne) SetUpdatedAt(v time.Time) *AlipayOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AlipayOrderMutation object of the builder.
func (_u *AlipayOrderUpdateOne) Mutation() *AlipayOrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the AlipayOrderUpdate builder.
func (_u *AlipayOrderUpdateOne) Where(ps ...predicate.AlipayOrder) *AlipayOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AlipayOrderUpdateOne) Select(field string, fields ...string) *AlipayOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AlipayOrder entity.
func (_u *AlipayOrderUpdateOne) Save(ctx context.Context) (*AlipayOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlipayOrderUpdateOne) SaveX(ctx context.Context) *AlipayOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AlipayOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlipayOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AlipayOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := alipayorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AlipayOrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := alipayorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "AlipayOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := alipayorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AlipayOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AlipayTradeNo(); ok {
		if err := alipayorder.AlipayTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "alipay_trade_no", err: fmt.Errorf(`ent: validator failed for field "AlipayOrder.alipay_trade_no": %w`, err)}
		}
	}
	return nil
}

func (_u *AlipayOrderUpdateOne) sqlSave(ctx context.Context) (_node *AlipayOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(alipayorder.Table, alipayorder.Columns, sqlgraph.NewFieldSpec(alipayorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AlipayOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, alipayorder.FieldID)
		for _, f := range fields {
			if !alipayorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != alipayorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(alipayorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(alipayorder.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(alipayorder.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(alipayorder.FieldPackageID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPackageID(); ok {
		_spec.AddField(alipayorder.FieldPackageID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CnyFee(); ok {
		_spec.SetField(alipayorder.FieldCnyFee, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCnyFee(); ok {
		_spec.AddField(alipayorder.FieldCnyFee, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsdAmount(); ok {
		_spec.SetField(alipayorder.FieldUsdAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsdAmount(); ok {
		_spec.AddField(alipayorder.FieldUsdAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(alipayorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AlipayTradeNo(); ok {
		_spec.SetField(alipayorder.FieldAlipayTradeNo, field.TypeString, value)
	}
	if _u.mutation.AlipayTradeNoCleared() {
		_spec.ClearField(alipayorder.FieldAlipayTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.QrCode(); ok {
		_spec.SetField(alipayorder.FieldQrCode, field.TypeString, value)
	}
	if _u.mutation.QrCodeCleared() {
		_spec.ClearField(alipayorder.FieldQrCode, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(alipayorder.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(alipayorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(alipayorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NotifyData(); ok {
		_spec.SetField(alipayorder.FieldNotifyData, field.TypeString, value)
	}
	if _u.mutation.NotifyDataCleared() {
		_spec.ClearField(alipayorder.FieldNotifyData, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(alipayorder.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AlipayOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alipayorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
