// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/alipayorder"
)

// AlipayOrderCreate is the builder for creating a AlipayOrder entity.
type AlipayOrderCreate struct {
	config
	mutation *AlipayOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrderNo sets the "order_no" field.
func (_c *AlipayOrderCreate) SetOrderNo(v string) *AlipayOrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AlipayOrderCreate) SetUserID(v int64) *AlipayOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPackageID sets the "package_id" field.
func (_c *AlipayOrderCreate) SetPackageID(v int) *AlipayOrderCreate {
	_c.mutation.SetPackageID(v)
	return _c
}

// SetCnyFee sets the "cny_fee" field.
func (_c *AlipayOrderCreate) SetCnyFee(v int) *AlipayOrderCreate {
	_c.mutation.SetCnyFee(v)
	return _c
}

// SetUsdAmount sets the "usd_amount" field.
func (_c *AlipayOrderCreate) SetUsdAmount(v float64) *AlipayOrderCreate {
	_c.mutation.SetUsdAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AlipayOrderCreate) SetStatus(v string) *AlipayOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AlipayOrderCreate) SetNillableStatus(v *string) *AlipayOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (_c *AlipayOrderCreate) SetAlipayTradeNo(v string) *AlipayOrderCreate {
	_c.mutation.SetAlipayTradeNo(v)
	return _c
}

// SetNillableAlipayTradeNo sets the "alipay_trade_no" field if the given value is not nil.
func (_c *AlipayOrderCreate) SetNillableAlipayTradeNo(v *string) *AlipayOrderCreate {
	if v != nil {
		_c.SetAlipayTradeNo(*v)
	}
	return _c
}

// SetQrCode sets the "qr_code" field.
func (_c *AlipayOrderCreate) SetQrCode(v string) *AlipayOrderCreate {
	_c.mutation.SetQrCode(v)
	return _c
}

// SetNillableQrCode sets the "qr_code" field if the given value is not nil.
func (_c *AlipayOrderCreate) SetNillableQrCode(v *string) *AlipayOrderCreate {
	if v != nil {
		_c.SetQrCode(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AlipayOrderCreate) SetExpiresAt(v time.Time) *AlipayOrderCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *AlipayOrderCreate) SetPaidAt(v time.Time) *AlipayOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *AlipayOrderCreate) SetNillablePaidAt(v *time.Time) *AlipayOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetNotifyData sets the "notify_data" field.
func (_c *AlipayOrderCreate) SetNotifyData(v string) *AlipayOrderCreate {
	_c.mutation.SetNotifyData(v)
	return _c
}

// SetNillableNotifyData sets the "notify_data" field if the given value is not nil.
func (_c *AlipayOrderCreate) SetNillableNotifyData(v *string) *AlipayOrderCreate {
	if v != nil {
		_c.SetNotifyData(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AlipayOrderCreate) SetCreatedAt(v time.Time) *AlipayOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AlipayOrderCreate) SetNillableCreatedAt(v *time.Time) *AlipayOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AlipayOrderCreate) SetUpdatedAt(v time.Time) *AlipayOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AlipayOrderCreate) SetNillableUpdatedAt(v *time.Time) *AlipayOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the AlipayOrderMutation object of the builder.
func (_c *AlipayOrderCreate) Mutation() *AlipayOrderMutation {
	return _c.mutation
}

// Save creates the AlipayOrder in the database.
func (_c *AlipayOrderCreate) Save(ctx context.Context) (*AlipayOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AlipayOrderCreate) SaveX(ctx context.Context) *AlipayOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AlipayOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AlipayOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AlipayOrderCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := alipayorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := alipayorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := alipayorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AlipayOrderCreate) check() error {
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "AlipayOrder.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := alipayorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "AlipayOrder.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AlipayOrder.user_id"`)}
	}
	if _, ok := _c.mutation.PackageID(); !ok {
		return &ValidationError{Name: "package_id", err: errors.New(`ent: missing required field "AlipayOrder.package_id"`)}
	}
	if _, ok := _c.mutation.CnyFee(); !ok {
		return &ValidationError{Name: "cny_fee", err: errors.New(`ent: missing required field "AlipayOrder.cny_fee"`)}
	}
	if _, ok := _c.mutation.UsdAmount(); !ok {
		return &ValidationError{Name: "usd_amount", err: errors.New(`ent: missing required field "AlipayOrder.usd_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AlipayOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := alipayorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AlipayOrder.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AlipayTradeNo(); ok {
		if err := alipayorder.AlipayTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "alipay_trade_no", err: fmt.Errorf(`ent: validator failed for field "AlipayOrder.alipay_trade_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AlipayOrder.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AlipayOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AlipayOrder.updated_at"`)}
	}
	return nil
}

func (_c *AlipayOrderCreate) sqlSave(ctx context.Context) (*AlipayOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AlipayOrderCreate) createSpec() (*AlipayOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &AlipayOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(alipayorder.Table, sqlgraph.NewFieldSpec(alipayorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(alipayorder.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(alipayorder.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.PackageID(); ok {
		_spec.SetField(alipayorder.FieldPackageID, field.TypeInt, value)
		_node.PackageID = value
	}
	if value, ok := _c.mutation.CnyFee(); ok {
		_spec.SetField(alipayorder.FieldCnyFee, field.TypeInt, value)
		_node.CnyFee = value
	}
	if value, ok := _c.mutation.UsdAmount(); ok {
		_spec.SetField(alipayorder.FieldUsdAmount, field.TypeFloat64, value)
		_node.UsdAmount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(alipayorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AlipayTradeNo(); ok {
		_spec.SetField(alipayorder.FieldAlipayTradeNo, field.TypeString, value)
		_node.AlipayTradeNo = &value
	}
	if value, ok := _c.mutation.QrCode(); ok {
		_spec.SetField(alipayorder.FieldQrCode, field.TypeString, value)
		_node.QrCode = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(alipayorder.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(alipayorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.NotifyData(); ok {
		_spec.SetField(alipayorder.FieldNotifyData, field.TypeString, value)
		_node.NotifyData = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(alipayorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(alipayorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AlipayOrder.Create().
//		SetOrderNo(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AlipayOrderUpsert) {
//			SetOrderNo(v+v).
//		}).
//		Exec(ctx)
func (_c *AlipayOrderCreate) OnConflict(opts ...sql.ConflictOption) *AlipayOrderUpsertOne {
	_c.conflict = opts
	return &AlipayOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AlipayOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AlipayOrderCreate) OnConflictColumns(columns ...string) *AlipayOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AlipayOrderUpsertOne{
		create: _c,
	}
}

type (
	// AlipayOrderUpsertOne is the builder for "upsert"-ing
	//  one AlipayOrder node.
	AlipayOrderUpsertOne struct {
		create *AlipayOrderCreate
	}

	// AlipayOrderUpsert is the "OnConflict" setter.
	AlipayOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrderNo sets the "order_no" field.
func (u *AlipayOrderUpsert) SetOrderNo(v string) *AlipayOrderUpsert {
	u.Set(alipayorder.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *AlipayOrderUpsert) UpdateOrderNo() *AlipayOrderUpsert {
	u.SetExcluded(alipayorder.FieldOrderNo)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AlipayOrderUpsert) SetUserID(v int64) *AlipayOrderUpsert {
	u.Set(alipayorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AlipayOrderUpsert) UpdateUserID() *AlipayOrderUpsert {
	u.SetExcluded(alipayorder.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *AlipayOrderUpsert) AddUserID(v int64) *AlipayOrderUpsert {
	u.Add(alipayorder.FieldUserID, v)
	return u
}

// SetPackageID sets the "package_id" field.
func (u *AlipayOrderUpsert) SetPackageID(v int) *AlipayOrderUpsert {
	u.Set(alipayorder.FieldPackageID, v)
	return u
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *AlipayOrderUpsert) UpdatePackageID() *AlipayOrderUpsert {
	u.SetExcluded(alipayorder.FieldPackageID)
	return u
}

// AddPackageID adds v to the "package_id" field.
func (u *AlipayOrderUpsert) AddPackageID(v int) *AlipayOrderUpsert {
	u.Add(alipayorder.FieldPackageID, v)
	return u
}

// SetCnyFee sets the "cny_fee" field.
func (u *AlipayOrderUpsert) SetCnyFee(v int) *AlipayOrderUpsert {
	u.Set(alipayorder.FieldCnyFee, v)
	return u
}

// UpdateCnyFee sets the "cny_fee" field to the value that was provided on create.
func (u *AlipayOrderUpsert) UpdateCnyFee() *AlipayOrderUpsert {
	u.SetExcluded(alipayorder.FieldCnyFee)
	return u
}

// AddCnyFee adds v to the "cny_fee" field.
func (u *AlipayOrderUpsert) AddCnyFee(v int) *AlipayOrderUpsert {
	u.Add(alipayorder.FieldCnyFee, v)
	return u
}

// SetUsdAmount sets the "usd_amount" field.
func (u *AlipayOrderUpsert) SetUsdAmount(v float64) *AlipayOrderUpsert {
	u.Set(alipayorder.FieldUsdAmount, v)
	return u
}

// UpdateUsdAmount sets the "usd_amount" field to the value that was provided on create.
func (u *AlipayOrderUpsert) UpdateUsdAmount() *AlipayOrderUpsert {
	u.SetExcluded(alipayorder.FieldUsdAmount)
	return u
}

// AddUsdAmount adds v to the "usd_amount" field.
func (u *AlipayOrderUpsert) AddUsdAmount(v float64) *AlipayOrderUpsert {
	u.Add(alipayorder.FieldUsdAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *AlipayOrderUpsert) SetStatus(v string) *AlipayOrderUpsert {
	u.Set(alipayorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AlipayOrderUpsert) UpdateStatus() *AlipayOrderUpsert {
	u.SetExcluded(alipayorder.FieldStatus)
	return u
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (u *AlipayOrderUpsert) SetAlipayTradeNo(v string) *AlipayOrderUpsert {
	u.Set(alipayorder.FieldAlipayTradeNo, v)
	return u
}

// UpdateAlipayTradeNo sets the "alipay_trade_no" field to the value that was provided on create.
func (u *AlipayOrderUpsert) UpdateAlipayTradeNo() *AlipayOrderUpsert {
	u.SetExcluded(alipayorder.FieldAlipayTradeNo)
	return u
}

// ClearAlipayTradeNo clears the value of the "alipay_trade_no" field.
func (u *AlipayOrderUpsert) ClearAlipayTradeNo() *AlipayOrderUpsert {
	u.SetNull(alipayorder.FieldAlipayTradeNo)
	return u
}

// SetQrCode sets the "qr_code" field.
func (u *AlipayOrderUpsert) SetQrCode(v string) *AlipayOrderUpsert {
	u.Set(alipayorder.FieldQrCode, v)
	return u
}

// UpdateQrCode sets the "qr_code" field to the value that was provided on create.
func (u *AlipayOrderUpsert) UpdateQrCode() *AlipayOrderUpsert {
	u.SetExcluded(alipayorder.FieldQrCode)
	return u
}

// ClearQrCode clears the value of the "qr_code" field.
func (u *AlipayOrderUpsert) ClearQrCode() *AlipayOrderUpsert {
	u.SetNull(alipayorder.FieldQrCode)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *AlipayOrderUpsert) SetExpiresAt(v time.Time) *AlipayOrderUpsert {
	u.Set(alipayorder.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AlipayOrderUpsert) UpdateExpiresAt() *AlipayOrderUpsert {
	u.SetExcluded(alipayorder.FieldExpiresAt)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *AlipayOrderUpsert) SetPaidAt(v time.Time) *AlipayOrderUpsert {
	u.Set(alipayorder.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *AlipayOrderUpsert) UpdatePaidAt() *AlipayOrderUpsert {
	u.SetExcluded(alipayorder.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *AlipayOrderUpsert) ClearPaidAt() *AlipayOrderUpsert {
	u.SetNull(alipayorder.FieldPaidAt)
	return u
}

// SetNotifyData sets the "notify_data" field.
func (u *AlipayOrderUpsert) SetNotifyData(v string) *AlipayOrderUpsert {
	u.Set(alipayorder.FieldNotifyData, v)
	return u
}

// UpdateNotifyData sets the "notify_data" field to the value that was provided on create.
func (u *AlipayOrderUpsert) UpdateNotifyData() *AlipayOrderUpsert {
	u.SetExcluded(alipayorder.FieldNotifyData)
	return u
}

// ClearNotifyData clears the value of the "notify_data" field.
func (u *AlipayOrderUpsert) ClearNotifyData() *AlipayOrderUpsert {
	u.SetNull(alipayorder.FieldNotifyData)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AlipayOrderUpsert) SetUpdatedAt(v time.Time) *AlipayOrderUpsert {
	u.Set(alipayorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AlipayOrderUpsert) UpdateUpdatedAt() *AlipayOrderUpsert {
	u.SetExcluded(alipayorder.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AlipayOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AlipayOrderUpsertOne) UpdateNewValues() *AlipayOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(alipayorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AlipayOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AlipayOrderUpsertOne) Ignore() *AlipayOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AlipayOrderUpsertOne) DoNothing() *AlipayOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AlipayOrderCreate.OnConflict
// documentation for more info.
func (u *AlipayOrderUpsertOne) Update(set func(*AlipayOrderUpsert)) *AlipayOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AlipayOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *AlipayOrderUpsertOne) SetOrderNo(v string) *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *AlipayOrderUpsertOne) UpdateOrderNo() *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *AlipayOrderUpsertOne) SetUserID(v int64) *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AlipayOrderUpsertOne) AddUserID(v int64) *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AlipayOrderUpsertOne) UpdateUserID() *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetPackageID sets the "package_id" field.
func (u *AlipayOrderUpsertOne) SetPackageID(v int) *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetPackageID(v)
	})
}

// AddPackageID adds v to the "package_id" field.
func (u *AlipayOrderUpsertOne) AddPackageID(v int) *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.AddPackageID(v)
	})
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *AlipayOrderUpsertOne) UpdatePackageID() *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdatePackageID()
	})
}

// SetCnyFee sets the "cny_fee" field.
func (u *AlipayOrderUpsertOne) SetCnyFee(v int) *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetCnyFee(v)
	})
}

// AddCnyFee adds v to the "cny_fee" field.
func (u *AlipayOrderUpsertOne) AddCnyFee(v int) *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.AddCnyFee(v)
	})
}

// UpdateCnyFee sets the "cny_fee" field to the value that was provided on create.
func (u *AlipayOrderUpsertOne) UpdateCnyFee() *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateCnyFee()
	})
}

// SetUsdAmount sets the "usd_amount" field.
func (u *AlipayOrderUpsertOne) SetUsdAmount(v float64) *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetUsdAmount(v)
	})
}

// AddUsdAmount adds v to the "usd_amount" field.
func (u *AlipayOrderUpsertOne) AddUsdAmount(v float64) *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.AddUsdAmount(v)
	})
}

// UpdateUsdAmount sets the "usd_amount" field to the value that was provided on create.
func (u *AlipayOrderUpsertOne) UpdateUsdAmount() *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateUsdAmount()
	})
}

// SetStatus sets the "status" field.
func (u *AlipayOrderUpsertOne) SetStatus(v string) *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AlipayOrderUpsertOne) UpdateStatus() *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (u *AlipayOrderUpsertOne) SetAlipayTradeNo(v string) *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetAlipayTradeNo(v)
	})
}

// UpdateAlipayTradeNo sets the "alipay_trade_no" field to the value that was provided on create.
func (u *AlipayOrderUpsertOne) UpdateAlipayTradeNo() *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateAlipayTradeNo()
	})
}

// ClearAlipayTradeNo clears the value of the "alipay_trade_no" field.
func (u *AlipayOrderUpsertOne) ClearAlipayTradeNo() *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.ClearAlipayTradeNo()
	})
}

// SetQrCode sets the "qr_code" field.
func (u *AlipayOrderUpsertOne) SetQrCode(v string) *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetQrCode(v)
	})
}

// UpdateQrCode sets the "qr_code" field to the value that was provided on create.
func (u *AlipayOrderUpsertOne) UpdateQrCode() *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateQrCode()
	})
}

// ClearQrCode clears the value of the "qr_code" field.
func (u *AlipayOrderUpsertOne) ClearQrCode() *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.ClearQrCode()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AlipayOrderUpsertOne) SetExpiresAt(v time.Time) *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AlipayOrderUpsertOne) UpdateExpiresAt() *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *AlipayOrderUpsertOne) SetPaidAt(v time.Time) *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *AlipayOrderUpsertOne) UpdatePaidAt() *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *AlipayOrderUpsertOne) ClearPaidAt() *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetNotifyData sets the "notify_data" field.
func (u *AlipayOrderUpsertOne) SetNotifyData(v string) *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetNotifyData(v)
	})
}

// UpdateNotifyData sets the "notify_data" field to the value that was provided on create.
func (u *AlipayOrderUpsertOne) UpdateNotifyData() *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateNotifyData()
	})
}

// ClearNotifyData clears the value of the "notify_data" field.
func (u *AlipayOrderUpsertOne) ClearNotifyData() *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.ClearNotifyData()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AlipayOrderUpsertOne) SetUpdatedAt(v time.Time) *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AlipayOrderUpsertOne) UpdateUpdatedAt() *AlipayOrderUpsertOne {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AlipayOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AlipayOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AlipayOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AlipayOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AlipayOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AlipayOrderCreateBulk is the builder for creating many AlipayOrder entities in bulk.
type AlipayOrderCreateBulk struct {
	config
	err      error
	builders []*AlipayOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the AlipayOrder entities in the database.
func (_c *AlipayOrderCreateBulk) Save(ctx context.Context) ([]*AlipayOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AlipayOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AlipayOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AlipayOrderCreateBulk) SaveX(ctx context.Context) []*AlipayOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AlipayOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AlipayOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AlipayOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AlipayOrderUpsert) {
//			SetOrderNo(v+v).
//		}).
//		Exec(ctx)
func (_c *AlipayOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *AlipayOrderUpsertBulk {
	_c.conflict = opts
	return &AlipayOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AlipayOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AlipayOrderCreateBulk) OnConflictColumns(columns ...string) *AlipayOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AlipayOrderUpsertBulk{
		create: _c,
	}
}

// AlipayOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of AlipayOrder nodes.
type AlipayOrderUpsertBulk struct {
	create *AlipayOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AlipayOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AlipayOrderUpsertBulk) UpdateNewValues() *AlipayOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(alipayorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AlipayOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AlipayOrderUpsertBulk) Ignore() *AlipayOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AlipayOrderUpsertBulk) DoNothing() *AlipayOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AlipayOrderCreateBulk.OnConflict
// documentation for more info.
func (u *AlipayOrderUpsertBulk) Update(set func(*AlipayOrderUpsert)) *AlipayOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AlipayOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *AlipayOrderUpsertBulk) SetOrderNo(v string) *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *AlipayOrderUpsertBulk) UpdateOrderNo() *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *AlipayOrderUpsertBulk) SetUserID(v int64) *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AlipayOrderUpsertBulk) AddUserID(v int64) *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AlipayOrderUpsertBulk) UpdateUserID() *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetPackageID sets the "package_id" field.
func (u *AlipayOrderUpsertBulk) SetPackageID(v int) *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetPackageID(v)
	})
}

// AddPackageID adds v to the "package_id" field.
func (u *AlipayOrderUpsertBulk) AddPackageID(v int) *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.AddPackageID(v)
	})
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *AlipayOrderUpsertBulk) UpdatePackageID() *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdatePackageID()
	})
}

// SetCnyFee sets the "cny_fee" field.
func (u *AlipayOrderUpsertBulk) SetCnyFee(v int) *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetCnyFee(v)
	})
}

// AddCnyFee adds v to the "cny_fee" field.
func (u *AlipayOrderUpsertBulk) AddCnyFee(v int) *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.AddCnyFee(v)
	})
}

// UpdateCnyFee sets the "cny_fee" field to the value that was provided on create.
func (u *AlipayOrderUpsertBulk) UpdateCnyFee() *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateCnyFee()
	})
}

// SetUsdAmount sets the "usd_amount" field.
func (u *AlipayOrderUpsertBulk) SetUsdAmount(v float64) *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetUsdAmount(v)
	})
}

// AddUsdAmount adds v to the "usd_amount" field.
func (u *AlipayOrderUpsertBulk) AddUsdAmount(v float64) *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.AddUsdAmount(v)
	})
}

// UpdateUsdAmount sets the "usd_amount" field to the value that was provided on create.
func (u *AlipayOrderUpsertBulk) UpdateUsdAmount() *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateUsdAmount()
	})
}

// SetStatus sets the "status" field.
func (u *AlipayOrderUpsertBulk) SetStatus(v string) *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AlipayOrderUpsertBulk) UpdateStatus() *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (u *AlipayOrderUpsertBulk) SetAlipayTradeNo(v string) *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetAlipayTradeNo(v)
	})
}

// UpdateAlipayTradeNo sets the "alipay_trade_no" field to the value that was provided on create.
func (u *AlipayOrderUpsertBulk) UpdateAlipayTradeNo() *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateAlipayTradeNo()
	})
}

// ClearAlipayTradeNo clears the value of the "alipay_trade_no" field.
func (u *AlipayOrderUpsertBulk) ClearAlipayTradeNo() *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.ClearAlipayTradeNo()
	})
}

// SetQrCode sets the "qr_code" field.
func (u *AlipayOrderUpsertBulk) SetQrCode(v string) *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetQrCode(v)
	})
}

// UpdateQrCode sets the "qr_code" field to the value that was provided on create.
func (u *AlipayOrderUpsertBulk) UpdateQrCode() *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateQrCode()
	})
}

// ClearQrCode clears the value of the "qr_code" field.
func (u *AlipayOrderUpsertBulk) ClearQrCode() *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.ClearQrCode()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AlipayOrderUpsertBulk) SetExpiresAt(v time.Time) *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AlipayOrderUpsertBulk) UpdateExpiresAt() *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *AlipayOrderUpsertBulk) SetPaidAt(v time.Time) *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *AlipayOrderUpsertBulk) UpdatePaidAt() *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *AlipayOrderUpsertBulk) ClearPaidAt() *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetNotifyData sets the "notify_data" field.
func (u *AlipayOrderUpsertBulk) SetNotifyData(v string) *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetNotifyData(v)
	})
}

// UpdateNotifyData sets the "notify_data" field to the value that was provided on create.
func (u *AlipayOrderUpsertBulk) UpdateNotifyData() *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateNotifyData()
	})
}

// ClearNotifyData clears the value of the "notify_data" field.
func (u *AlipayOrderUpsertBulk) ClearNotifyData() *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.ClearNotifyData()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AlipayOrderUpsertBulk) SetUpdatedAt(v time.Time) *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AlipayOrderUpsertBulk) UpdateUpdatedAt() *AlipayOrderUpsertBulk {
	return u.Update(func(s *AlipayOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AlipayOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AlipayOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AlipayOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AlipayOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
