// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/alipayorder"
)

// AlipayOrder is the model entity for the AlipayOrder schema.
type AlipayOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// OrderNo holds the value of the "order_no" field.
	OrderNo string `json:"order_no,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// PackageID holds the value of the "package_id" field.
	PackageID int `json:"package_id,omitempty"`
	// CnyFee holds the value of the "cny_fee" field.
	CnyFee int `json:"cny_fee,omitempty"`
	// UsdAmount holds the value of the "usd_amount" field.
	UsdAmount float64 `json:"usd_amount,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AlipayTradeNo holds the value of the "alipay_trade_no" field.
	AlipayTradeNo *string `json:"alipay_trade_no,omitempty"`
	// QrCode holds the value of the "qr_code" field.
	QrCode *string `json:"qr_code,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// NotifyData holds the value of the "notify_data" field.
	NotifyData *string `json:"notify_data,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AlipayOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case alipayorder.FieldUsdAmount:
			values[i] = new(sql.NullFloat64)
		case alipayorder.FieldID, alipayorder.FieldUserID, alipayorder.FieldPackageID, alipayorder.FieldCnyFee:
			values[i] = new(sql.NullInt64)
		case alipayorder.FieldOrderNo, alipayorder.FieldStatus, alipayorder.FieldAlipayTradeNo, alipayorder.FieldQrCode, alipayorder.FieldNotifyData:
			values[i] = new(sql.NullString)
		case alipayorder.FieldExpiresAt, alipayorder.FieldPaidAt, alipayorder.FieldCreatedAt, alipayorder.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AlipayOrder fields.
func (_m *AlipayOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case alipayorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case alipayorder.FieldOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_no", values[i])
			} else if value.Valid {
				_m.OrderNo = value.String
			}
		case alipayorder.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case alipayorder.FieldPackageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field package_id", values[i])
			} else if value.Valid {
				_m.PackageID = int(value.Int64)
			}
		case alipayorder.FieldCnyFee:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cny_fee", values[i])
			} else if value.Valid {
				_m.CnyFee = int(value.Int64)
			}
		case alipayorder.FieldUsdAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field usd_amount", values[i])
			} else if value.Valid {
				_m.UsdAmount = value.Float64
			}
		case alipayorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case alipayorder.FieldAlipayTradeNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alipay_trade_no", values[i])
			} else if value.Valid {
				_m.AlipayTradeNo = new(string)
				*_m.AlipayTradeNo = value.String
			}
		case alipayorder.FieldQrCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field qr_code", values[i])
			} else if value.Valid {
				_m.QrCode = new(string)
				*_m.QrCode = value.String
			}
		case alipayorder.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case alipayorder.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case alipayorder.FieldNotifyData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notify_data", values[i])
			} else if value.Valid {
				_m.NotifyData = new(string)
				*_m.NotifyData = value.String
			}
		case alipayorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case alipayorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AlipayOrder.
// This includes values selected through modifiers, order, etc.
func (_m *AlipayOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AlipayOrder.
// Note that you need to call AlipayOrder.Unwrap() before calling this method if this AlipayOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AlipayOrder) Update() *AlipayOrderUpdateOne {
	return NewAlipayOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AlipayOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AlipayOrder) Unwrap() *AlipayOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AlipayOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AlipayOrder) String() string {
	var builder strings.Builder
	builder.WriteString("AlipayOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("order_no=")
	builder.WriteString(_m.OrderNo)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("package_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PackageID))
	builder.WriteString(", ")
	builder.WriteString("cny_fee=")
	builder.WriteString(fmt.Sprintf("%v", _m.CnyFee))
	builder.WriteString(", ")
	builder.WriteString("usd_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsdAmount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.AlipayTradeNo; v != nil {
		builder.WriteString("alipay_trade_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.QrCode; v != nil {
		builder.WriteString("qr_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NotifyData; v != nil {
		builder.WriteString("notify_data=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AlipayOrders is a parsable slice of AlipayOrder.
type AlipayOrders []*AlipayOrder
