// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionPlanUpdate is the builder for updating SubscriptionPlan entities.
type SubscriptionPlanUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionPlanMutation
}

// Where appends a list predicates to the SubscriptionPlanUpdate builder.
func (_u *SubscriptionPlanUpdate) Where(ps ...predicate.SubscriptionPlan) *SubscriptionPlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionPlanUpdate) SetUpdatedAt(v time.Time) *SubscriptionPlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SubscriptionPlanUpdate) SetDeletedAt(v time.Time) *SubscriptionPlanUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableDeletedAt(v *time.Time) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SubscriptionPlanUpdate) ClearDeletedAt() *SubscriptionPlanUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *SubscriptionPlanUpdate) SetName(v string) *SubscriptionPlanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableName(v *string) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SubscriptionPlanUpdate) SetDescription(v string) *SubscriptionPlanUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableDescription(v *string) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SubscriptionPlanUpdate) ClearDescription() *SubscriptionPlanUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *SubscriptionPlanUpdate) SetVisibility(v string) *SubscriptionPlanUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableVisibility(v *string) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionPlanUpdate) SetStatus(v string) *SubscriptionPlanUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableStatus(v *string) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_u *SubscriptionPlanUpdate) SetDailyLimitUsd(v float64) *SubscriptionPlanUpdate {
	_u.mutation.ResetDailyLimitUsd()
	_u.mutation.SetDailyLimitUsd(v)
	return _u
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableDailyLimitUsd(v *float64) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetDailyLimitUsd(*v)
	}
	return _u
}

// AddDailyLimitUsd adds value to the "daily_limit_usd" field.
func (_u *SubscriptionPlanUpdate) AddDailyLimitUsd(v float64) *SubscriptionPlanUpdate {
	_u.mutation.AddDailyLimitUsd(v)
	return _u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (_u *SubscriptionPlanUpdate) ClearDailyLimitUsd() *SubscriptionPlanUpdate {
	_u.mutation.ClearDailyLimitUsd()
	return _u
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (_u *SubscriptionPlanUpdate) SetWeeklyLimitUsd(v float64) *SubscriptionPlanUpdate {
	_u.mutation.ResetWeeklyLimitUsd()
	_u.mutation.SetWeeklyLimitUsd(v)
	return _u
}

// SetNillableWeeklyLimitUsd sets the "weekly_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableWeeklyLimitUsd(v *float64) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetWeeklyLimitUsd(*v)
	}
	return _u
}

// AddWeeklyLimitUsd adds value to the "weekly_limit_usd" field.
func (_u *SubscriptionPlanUpdate) AddWeeklyLimitUsd(v float64) *SubscriptionPlanUpdate {
	_u.mutation.AddWeeklyLimitUsd(v)
	return _u
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (_u *SubscriptionPlanUpdate) ClearWeeklyLimitUsd() *SubscriptionPlanUpdate {
	_u.mutation.ClearWeeklyLimitUsd()
	return _u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_u *SubscriptionPlanUpdate) SetMonthlyLimitUsd(v float64) *SubscriptionPlanUpdate {
	_u.mutation.ResetMonthlyLimitUsd()
	_u.mutation.SetMonthlyLimitUsd(v)
	return _u
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableMonthlyLimitUsd(v *float64) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetMonthlyLimitUsd(*v)
	}
	return _u
}

// AddMonthlyLimitUsd adds value to the "monthly_limit_usd" field.
func (_u *SubscriptionPlanUpdate) AddMonthlyLimitUsd(v float64) *SubscriptionPlanUpdate {
	_u.mutation.AddMonthlyLimitUsd(v)
	return _u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (_u *SubscriptionPlanUpdate) ClearMonthlyLimitUsd() *SubscriptionPlanUpdate {
	_u.mutation.ClearMonthlyLimitUsd()
	return _u
}

// SetDefaultValidityDays sets the "default_validity_days" field.
func (_u *SubscriptionPlanUpdate) SetDefaultValidityDays(v int) *SubscriptionPlanUpdate {
	_u.mutation.ResetDefaultValidityDays()
	_u.mutation.SetDefaultValidityDays(v)
	return _u
}

// SetNillableDefaultValidityDays sets the "default_validity_days" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableDefaultValidityDays(v *int) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetDefaultValidityDays(*v)
	}
	return _u
}

// AddDefaultValidityDays adds value to the "default_validity_days" field.
func (_u *SubscriptionPlanUpdate) AddDefaultValidityDays(v int) *SubscriptionPlanUpdate {
	_u.mutation.AddDefaultValidityDays(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *SubscriptionPlanUpdate) SetPrice(v float64) *SubscriptionPlanUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillablePrice(v *float64) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *SubscriptionPlanUpdate) AddPrice(v float64) *SubscriptionPlanUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// ClearPrice clears the value of the "price" field.
func (_u *SubscriptionPlanUpdate) ClearPrice() *SubscriptionPlanUpdate {
	_u.mutation.ClearPrice()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SubscriptionPlanUpdate) SetSortOrder(v int) *SubscriptionPlanUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableSortOrder(v *int) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SubscriptionPlanUpdate) AddSortOrder(v int) *SubscriptionPlanUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddSubscriptionIDs adds the "subscriptions" edge to the UserSubscription entity by IDs.
func (_u *SubscriptionPlanUpdate) AddSubscriptionIDs(ids ...int64) *SubscriptionPlanUpdate {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the UserSubscription entity.
func (_u *SubscriptionPlanUpdate) AddSubscriptions(v ...*UserSubscription) *SubscriptionPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// AddRedeemCodeIDs adds the "redeem_codes" edge to the RedeemCode entity by IDs.
func (_u *SubscriptionPlanUpdate) AddRedeemCodeIDs(ids ...int64) *SubscriptionPlanUpdate {
	_u.mutation.AddRedeemCodeIDs(ids...)
	return _u
}

// AddRedeemCodes adds the "redeem_codes" edges to the RedeemCode entity.
func (_u *SubscriptionPlanUpdate) AddRedeemCodes(v ...*RedeemCode) *SubscriptionPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRedeemCodeIDs(ids...)
}

// Mutation returns the SubscriptionPlanMutation object of the builder.
func (_u *SubscriptionPlanUpdate) Mutation() *SubscriptionPlanMutation {
	return _u.mutation
}

// ClearSubscriptions clears all "subscriptions" edges to the UserSubscription entity.
func (_u *SubscriptionPlanUpdate) ClearSubscriptions() *SubscriptionPlanUpdate {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to UserSubscription entities by IDs.
func (_u *SubscriptionPlanUpdate) RemoveSubscriptionIDs(ids ...int64) *SubscriptionPlanUpdate {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to UserSubscription entities.
func (_u *SubscriptionPlanUpdate) RemoveSubscriptions(v ...*UserSubscription) *SubscriptionPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// ClearRedeemCodes clears all "redeem_codes" edges to the RedeemCode entity.
func (_u *SubscriptionPlanUpdate) ClearRedeemCodes() *SubscriptionPlanUpdate {
	_u.mutation.ClearRedeemCodes()
	return _u
}

// RemoveRedeemCodeIDs removes the "redeem_codes" edge to RedeemCode entities by IDs.
func (_u *SubscriptionPlanUpdate) RemoveRedeemCodeIDs(ids ...int64) *SubscriptionPlanUpdate {
	_u.mutation.RemoveRedeemCodeIDs(ids...)
	return _u
}

// RemoveRedeemCodes removes "redeem_codes" edges to RedeemCode entities.
func (_u *SubscriptionPlanUpdate) RemoveRedeemCodes(v ...*RedeemCode) *SubscriptionPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRedeemCodeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionPlanUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionPlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionPlanUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if subscriptionplan.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized subscriptionplan.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := subscriptionplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionPlanUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := subscriptionplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := subscriptionplan.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.visibility": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionplan.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionPlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionplan.Table, subscriptionplan.Columns, sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(subscriptionplan.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(subscriptionplan.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subscriptionplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(subscriptionplan.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(subscriptionplan.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(subscriptionplan.FieldVisibility, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionplan.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyLimitUsd(); ok {
		_spec.SetField(subscriptionplan.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsd(); ok {
		_spec.AddField(subscriptionplan.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.DailyLimitUsdCleared() {
		_spec.ClearField(subscriptionplan.FieldDailyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WeeklyLimitUsd(); ok {
		_spec.SetField(subscriptionplan.FieldWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyLimitUsd(); ok {
		_spec.AddField(subscriptionplan.FieldWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.WeeklyLimitUsdCleared() {
		_spec.ClearField(subscriptionplan.FieldWeeklyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(subscriptionplan.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyLimitUsd(); ok {
		_spec.AddField(subscriptionplan.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.MonthlyLimitUsdCleared() {
		_spec.ClearField(subscriptionplan.FieldMonthlyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DefaultValidityDays(); ok {
		_spec.SetField(subscriptionplan.FieldDefaultValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDefaultValidityDays(); ok {
		_spec.AddField(subscriptionplan.FieldDefaultValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(subscriptionplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(subscriptionplan.FieldPrice, field.TypeFloat64, value)
	}
	if _u.mutation.PriceCleared() {
		_spec.ClearField(subscriptionplan.FieldPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.SubscriptionsTable,
			Columns: []string{subscriptionplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.SubscriptionsTable,
			Columns: []string{subscriptionplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.SubscriptionsTable,
			Columns: []string{subscriptionplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.RedeemCodesTable,
			Columns: []string{subscriptionplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRedeemCodesIDs(); len(nodes) > 0 && !_u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.RedeemCodesTable,
			Columns: []string{subscriptionplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedeemCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.RedeemCodesTable,
			Columns: []string{subscriptionplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionPlanUpdateOne is the builder for updating a single SubscriptionPlan entity.
type SubscriptionPlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionPlanMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionPlanUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionPlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SubscriptionPlanUpdateOne) SetDeletedAt(v time.Time) *SubscriptionPlanUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableDeletedAt(v *time.Time) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SubscriptionPlanUpdateOne) ClearDeletedAt() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *SubscriptionPlanUpdateOne) SetName(v string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableName(v *string) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SubscriptionPlanUpdateOne) SetDescription(v string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableDescription(v *string) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SubscriptionPlanUpdateOne) ClearDescription() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *SubscriptionPlanUpdateOne) SetVisibility(v string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableVisibility(v *string) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionPlanUpdateOne) SetStatus(v string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableStatus(v *string) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) SetDailyLimitUsd(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetDailyLimitUsd()
	_u.mutation.SetDailyLimitUsd(v)
	return _u
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableDailyLimitUsd(v *float64) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetDailyLimitUsd(*v)
	}
	return _u
}

// AddDailyLimitUsd adds value to the "daily_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) AddDailyLimitUsd(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddDailyLimitUsd(v)
	return _u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) ClearDailyLimitUsd() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearDailyLimitUsd()
	return _u
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) SetWeeklyLimitUsd(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetWeeklyLimitUsd()
	_u.mutation.SetWeeklyLimitUsd(v)
	return _u
}

// SetNillableWeeklyLimitUsd sets the "weekly_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableWeeklyLimitUsd(v *float64) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetWeeklyLimitUsd(*v)
	}
	return _u
}

// AddWeeklyLimitUsd adds value to the "weekly_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) AddWeeklyLimitUsd(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddWeeklyLimitUsd(v)
	return _u
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) ClearWeeklyLimitUsd() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearWeeklyLimitUsd()
	return _u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) SetMonthlyLimitUsd(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetMonthlyLimitUsd()
	_u.mutation.SetMonthlyLimitUsd(v)
	return _u
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableMonthlyLimitUsd(v *float64) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetMonthlyLimitUsd(*v)
	}
	return _u
}

// AddMonthlyLimitUsd adds value to the "monthly_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) AddMonthlyLimitUsd(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddMonthlyLimitUsd(v)
	return _u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) ClearMonthlyLimitUsd() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearMonthlyLimitUsd()
	return _u
}

// SetDefaultValidityDays sets the "default_validity_days" field.
func (_u *SubscriptionPlanUpdateOne) SetDefaultValidityDays(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetDefaultValidityDays()
	_u.mutation.SetDefaultValidityDays(v)
	return _u
}

// SetNillableDefaultValidityDays sets the "default_validity_days" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableDefaultValidityDays(v *int) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetDefaultValidityDays(*v)
	}
	return _u
}

// AddDefaultValidityDays adds value to the "default_validity_days" field.
func (_u *SubscriptionPlanUpdateOne) AddDefaultValidityDays(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.AddDefaultValidityDays(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *SubscriptionPlanUpdateOne) SetPrice(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillablePrice(v *float64) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *SubscriptionPlanUpdateOne) AddPrice(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// ClearPrice clears the value of the "price" field.
func (_u *SubscriptionPlanUpdateOne) ClearPrice() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearPrice()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SubscriptionPlanUpdateOne) SetSortOrder(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableSortOrder(v *int) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SubscriptionPlanUpdateOne) AddSortOrder(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddSubscriptionIDs adds the "subscriptions" edge to the UserSubscription entity by IDs.
func (_u *SubscriptionPlanUpdateOne) AddSubscriptionIDs(ids ...int64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the UserSubscription entity.
func (_u *SubscriptionPlanUpdateOne) AddSubscriptions(v ...*UserSubscription) *SubscriptionPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// AddRedeemCodeIDs adds the "redeem_codes" edge to the RedeemCode entity by IDs.
func (_u *SubscriptionPlanUpdateOne) AddRedeemCodeIDs(ids ...int64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddRedeemCodeIDs(ids...)
	return _u
}

// AddRedeemCodes adds the "redeem_codes" edges to the RedeemCode entity.
func (_u *SubscriptionPlanUpdateOne) AddRedeemCodes(v ...*RedeemCode) *SubscriptionPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRedeemCodeIDs(ids...)
}

// Mutation returns the SubscriptionPlanMutation object of the builder.
func (_u *SubscriptionPlanUpdateOne) Mutation() *SubscriptionPlanMutation {
	return _u.mutation
}

// ClearSubscriptions clears all "subscriptions" edges to the UserSubscription entity.
func (_u *SubscriptionPlanUpdateOne) ClearSubscriptions() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to UserSubscription entities by IDs.
func (_u *SubscriptionPlanUpdateOne) RemoveSubscriptionIDs(ids ...int64) *SubscriptionPlanUpdateOne {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to UserSubscription entities.
func (_u *SubscriptionPlanUpdateOne) RemoveSubscriptions(v ...*UserSubscription) *SubscriptionPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// ClearRedeemCodes clears all "redeem_codes" edges to the RedeemCode entity.
func (_u *SubscriptionPlanUpdateOne) ClearRedeemCodes() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearRedeemCodes()
	return _u
}

// RemoveRedeemCodeIDs removes the "redeem_codes" edge to RedeemCode entities by IDs.
func (_u *SubscriptionPlanUpdateOne) RemoveRedeemCodeIDs(ids ...int64) *SubscriptionPlanUpdateOne {
	_u.mutation.RemoveRedeemCodeIDs(ids...)
	return _u
}

// RemoveRedeemCodes removes "redeem_codes" edges to RedeemCode entities.
func (_u *SubscriptionPlanUpdateOne) RemoveRedeemCodes(v ...*RedeemCode) *SubscriptionPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRedeemCodeIDs(ids...)
}

// Where appends a list predicates to the SubscriptionPlanUpdate builder.
func (_u *SubscriptionPlanUpdateOne) Where(ps ...predicate.SubscriptionPlan) *SubscriptionPlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionPlanUpdateOne) Select(field string, fields ...string) *SubscriptionPlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionPlan entity.
func (_u *SubscriptionPlanUpdateOne) Save(ctx context.Context) (*SubscriptionPlan, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPlanUpdateOne) SaveX(ctx context.Context) *SubscriptionPlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionPlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionPlanUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if subscriptionplan.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized subscriptionplan.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := subscriptionplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionPlanUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := subscriptionplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := subscriptionplan.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.visibility": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionplan.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionPlanUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionPlan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionplan.Table, subscriptionplan.Columns, sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionPlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionplan.FieldID)
		for _, f := range fields {
			if !subscriptionplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(subscriptionplan.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(subscriptionplan.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subscriptionplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(subscriptionplan.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(subscriptionplan.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(subscriptionplan.FieldVisibility, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionplan.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyLimitUsd(); ok {
		_spec.SetField(subscriptionplan.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsd(); ok {
		_spec.AddField(subscriptionplan.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.DailyLimitUsdCleared() {
		_spec.ClearField(subscriptionplan.FieldDailyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WeeklyLimitUsd(); ok {
		_spec.SetField(subscriptionplan.FieldWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyLimitUsd(); ok {
		_spec.AddField(subscriptionplan.FieldWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.WeeklyLimitUsdCleared() {
		_spec.ClearField(subscriptionplan.FieldWeeklyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(subscriptionplan.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyLimitUsd(); ok {
		_spec.AddField(subscriptionplan.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.MonthlyLimitUsdCleared() {
		_spec.ClearField(subscriptionplan.FieldMonthlyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DefaultValidityDays(); ok {
		_spec.SetField(subscriptionplan.FieldDefaultValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDefaultValidityDays(); ok {
		_spec.AddField(subscriptionplan.FieldDefaultValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(subscriptionplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(subscriptionplan.FieldPrice, field.TypeFloat64, value)
	}
	if _u.mutation.PriceCleared() {
		_spec.ClearField(subscriptionplan.FieldPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.SubscriptionsTable,
			Columns: []string{subscriptionplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.SubscriptionsTable,
			Columns: []string{subscriptionplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.SubscriptionsTable,
			Columns: []string{subscriptionplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.RedeemCodesTable,
			Columns: []string{subscriptionplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRedeemCodesIDs(); len(nodes) > 0 && !_u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.RedeemCodesTable,
			Columns: []string{subscriptionplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedeemCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.RedeemCodesTable,
			Columns: []string{subscriptionplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionPlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
