// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionPlanCreate is the builder for creating a SubscriptionPlan entity.
type SubscriptionPlanCreate struct {
	config
	mutation *SubscriptionPlanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionPlanCreate) SetCreatedAt(v time.Time) *SubscriptionPlanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionPlanCreate) SetUpdatedAt(v time.Time) *SubscriptionPlanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SubscriptionPlanCreate) SetDeletedAt(v time.Time) *SubscriptionPlanCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableDeletedAt(v *time.Time) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *SubscriptionPlanCreate) SetName(v string) *SubscriptionPlanCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SubscriptionPlanCreate) SetDescription(v string) *SubscriptionPlanCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableDescription(v *string) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetVisibility sets the "visibility" field.
func (_c *SubscriptionPlanCreate) SetVisibility(v string) *SubscriptionPlanCreate {
	_c.mutation.SetVisibility(v)
	return _c
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableVisibility(v *string) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetVisibility(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubscriptionPlanCreate) SetStatus(v string) *SubscriptionPlanCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableStatus(v *string) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_c *SubscriptionPlanCreate) SetDailyLimitUsd(v float64) *SubscriptionPlanCreate {
	_c.mutation.SetDailyLimitUsd(v)
	return _c
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableDailyLimitUsd(v *float64) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetDailyLimitUsd(*v)
	}
	return _c
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (_c *SubscriptionPlanCreate) SetWeeklyLimitUsd(v float64) *SubscriptionPlanCreate {
	_c.mutation.SetWeeklyLimitUsd(v)
	return _c
}

// SetNillableWeeklyLimitUsd sets the "weekly_limit_usd" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableWeeklyLimitUsd(v *float64) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetWeeklyLimitUsd(*v)
	}
	return _c
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_c *SubscriptionPlanCreate) SetMonthlyLimitUsd(v float64) *SubscriptionPlanCreate {
	_c.mutation.SetMonthlyLimitUsd(v)
	return _c
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableMonthlyLimitUsd(v *float64) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetMonthlyLimitUsd(*v)
	}
	return _c
}

// SetDefaultValidityDays sets the "default_validity_days" field.
func (_c *SubscriptionPlanCreate) SetDefaultValidityDays(v int) *SubscriptionPlanCreate {
	_c.mutation.SetDefaultValidityDays(v)
	return _c
}

// SetNillableDefaultValidityDays sets the "default_validity_days" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableDefaultValidityDays(v *int) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetDefaultValidityDays(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *SubscriptionPlanCreate) SetPrice(v float64) *SubscriptionPlanCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillablePrice(v *float64) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetPrice(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *SubscriptionPlanCreate) SetSortOrder(v int) *SubscriptionPlanCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableSortOrder(v *int) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// AddSubscriptionIDs adds the "subscriptions" edge to the UserSubscription entity by IDs.
func (_c *SubscriptionPlanCreate) AddSubscriptionIDs(ids ...int64) *SubscriptionPlanCreate {
	_c.mutation.AddSubscriptionIDs(ids...)
	return _c
}

// AddSubscriptions adds the "subscriptions" edges to the UserSubscription entity.
func (_c *SubscriptionPlanCreate) AddSubscriptions(v ...*UserSubscription) *SubscriptionPlanCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubscriptionIDs(ids...)
}

// AddRedeemCodeIDs adds the "redeem_codes" edge to the RedeemCode entity by IDs.
func (_c *SubscriptionPlanCreate) AddRedeemCodeIDs(ids ...int64) *SubscriptionPlanCreate {
	_c.mutation.AddRedeemCodeIDs(ids...)
	return _c
}

// AddRedeemCodes adds the "redeem_codes" edges to the RedeemCode entity.
func (_c *SubscriptionPlanCreate) AddRedeemCodes(v ...*RedeemCode) *SubscriptionPlanCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRedeemCodeIDs(ids...)
}

// Mutation returns the SubscriptionPlanMutation object of the builder.
func (_c *SubscriptionPlanCreate) Mutation() *SubscriptionPlanMutation {
	return _c.mutation
}

// Save creates the SubscriptionPlan in the database.
func (_c *SubscriptionPlanCreate) Save(ctx context.Context) (*SubscriptionPlan, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionPlanCreate) SaveX(ctx context.Context) *SubscriptionPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionPlanCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if subscriptionplan.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized subscriptionplan.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := subscriptionplan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if subscriptionplan.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized subscriptionplan.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := subscriptionplan.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		v := subscriptionplan.DefaultVisibility
		_c.mutation.SetVisibility(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := subscriptionplan.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DefaultValidityDays(); !ok {
		v := subscriptionplan.DefaultDefaultValidityDays
		_c.mutation.SetDefaultValidityDays(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := subscriptionplan.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionPlanCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionPlan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionPlan.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SubscriptionPlan.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := subscriptionplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`ent: missing required field "SubscriptionPlan.visibility"`)}
	}
	if v, ok := _c.mutation.Visibility(); ok {
		if err := subscriptionplan.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.visibility": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SubscriptionPlan.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := subscriptionplan.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultValidityDays(); !ok {
		return &ValidationError{Name: "default_validity_days", err: errors.New(`ent: missing required field "SubscriptionPlan.default_validity_days"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "SubscriptionPlan.sort_order"`)}
	}
	return nil
}

func (_c *SubscriptionPlanCreate) sqlSave(ctx context.Context) (*SubscriptionPlan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionPlanCreate) createSpec() (*SubscriptionPlan, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionPlan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionplan.Table, sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionplan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionplan.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(subscriptionplan.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(subscriptionplan.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(subscriptionplan.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Visibility(); ok {
		_spec.SetField(subscriptionplan.FieldVisibility, field.TypeString, value)
		_node.Visibility = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subscriptionplan.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DailyLimitUsd(); ok {
		_spec.SetField(subscriptionplan.FieldDailyLimitUsd, field.TypeFloat64, value)
		_node.DailyLimitUsd = &value
	}
	if value, ok := _c.mutation.WeeklyLimitUsd(); ok {
		_spec.SetField(subscriptionplan.FieldWeeklyLimitUsd, field.TypeFloat64, value)
		_node.WeeklyLimitUsd = &value
	}
	if value, ok := _c.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(subscriptionplan.FieldMonthlyLimitUsd, field.TypeFloat64, value)
		_node.MonthlyLimitUsd = &value
	}
	if value, ok := _c.mutation.DefaultValidityDays(); ok {
		_spec.SetField(subscriptionplan.FieldDefaultValidityDays, field.TypeInt, value)
		_node.DefaultValidityDays = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(subscriptionplan.FieldPrice, field.TypeFloat64, value)
		_node.Price = &value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.SubscriptionsTable,
			Columns: []string{subscriptionplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RedeemCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.RedeemCodesTable,
			Columns: []string{subscriptionplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionPlan.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionPlanUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionPlanCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionPlanUpsertOne {
	_c.conflict = opts
	return &SubscriptionPlanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionPlanCreate) OnConflictColumns(columns ...string) *SubscriptionPlanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionPlanUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionPlanUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionPlan node.
	SubscriptionPlanUpsertOne struct {
		create *SubscriptionPlanCreate
	}

	// SubscriptionPlanUpsert is the "OnConflict" setter.
	SubscriptionPlanUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionPlanUpsert) SetUpdatedAt(v time.Time) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateUpdatedAt() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionPlanUpsert) SetDeletedAt(v time.Time) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateDeletedAt() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubscriptionPlanUpsert) ClearDeletedAt() *SubscriptionPlanUpsert {
	u.SetNull(subscriptionplan.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *SubscriptionPlanUpsert) SetName(v string) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateName() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *SubscriptionPlanUpsert) SetDescription(v string) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateDescription() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *SubscriptionPlanUpsert) ClearDescription() *SubscriptionPlanUpsert {
	u.SetNull(subscriptionplan.FieldDescription)
	return u
}

// SetVisibility sets the "visibility" field.
func (u *SubscriptionPlanUpsert) SetVisibility(v string) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldVisibility, v)
	return u
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateVisibility() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldVisibility)
	return u
}

// SetStatus sets the "status" field.
func (u *SubscriptionPlanUpsert) SetStatus(v string) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateStatus() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldStatus)
	return u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *SubscriptionPlanUpsert) SetDailyLimitUsd(v float64) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldDailyLimitUsd, v)
	return u
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateDailyLimitUsd() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldDailyLimitUsd)
	return u
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *SubscriptionPlanUpsert) AddDailyLimitUsd(v float64) *SubscriptionPlanUpsert {
	u.Add(subscriptionplan.FieldDailyLimitUsd, v)
	return u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *SubscriptionPlanUpsert) ClearDailyLimitUsd() *SubscriptionPlanUpsert {
	u.SetNull(subscriptionplan.FieldDailyLimitUsd)
	return u
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *SubscriptionPlanUpsert) SetWeeklyLimitUsd(v float64) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldWeeklyLimitUsd, v)
	return u
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateWeeklyLimitUsd() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldWeeklyLimitUsd)
	return u
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *SubscriptionPlanUpsert) AddWeeklyLimitUsd(v float64) *SubscriptionPlanUpsert {
	u.Add(subscriptionplan.FieldWeeklyLimitUsd, v)
	return u
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (u *SubscriptionPlanUpsert) ClearWeeklyLimitUsd() *SubscriptionPlanUpsert {
	u.SetNull(subscriptionplan.FieldWeeklyLimitUsd)
	return u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *SubscriptionPlanUpsert) SetMonthlyLimitUsd(v float64) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldMonthlyLimitUsd, v)
	return u
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateMonthlyLimitUsd() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldMonthlyLimitUsd)
	return u
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *SubscriptionPlanUpsert) AddMonthlyLimitUsd(v float64) *SubscriptionPlanUpsert {
	u.Add(subscriptionplan.FieldMonthlyLimitUsd, v)
	return u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *SubscriptionPlanUpsert) ClearMonthlyLimitUsd() *SubscriptionPlanUpsert {
	u.SetNull(subscriptionplan.FieldMonthlyLimitUsd)
	return u
}

// SetDefaultValidityDays sets the "default_validity_days" field.
func (u *SubscriptionPlanUpsert) SetDefaultValidityDays(v int) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldDefaultValidityDays, v)
	return u
}

// UpdateDefaultValidityDays sets the "default_validity_days" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateDefaultValidityDays() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldDefaultValidityDays)
	return u
}

// AddDefaultValidityDays adds v to the "default_validity_days" field.
func (u *SubscriptionPlanUpsert) AddDefaultValidityDays(v int) *SubscriptionPlanUpsert {
	u.Add(subscriptionplan.FieldDefaultValidityDays, v)
	return u
}

// SetPrice sets the "price" field.
func (u *SubscriptionPlanUpsert) SetPrice(v float64) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdatePrice() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *SubscriptionPlanUpsert) AddPrice(v float64) *SubscriptionPlanUpsert {
	u.Add(subscriptionplan.FieldPrice, v)
	return u
}

// ClearPrice clears the value of the "price" field.
func (u *SubscriptionPlanUpsert) ClearPrice() *SubscriptionPlanUpsert {
	u.SetNull(subscriptionplan.FieldPrice)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *SubscriptionPlanUpsert) SetSortOrder(v int) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateSortOrder() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SubscriptionPlanUpsert) AddSortOrder(v int) *SubscriptionPlanUpsert {
	u.Add(subscriptionplan.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionPlanUpsertOne) UpdateNewValues() *SubscriptionPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionplan.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionPlanUpsertOne) Ignore() *SubscriptionPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionPlanUpsertOne) DoNothing() *SubscriptionPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionPlanCreate.OnConflict
// documentation for more info.
func (u *SubscriptionPlanUpsertOne) Update(set func(*SubscriptionPlanUpsert)) *SubscriptionPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionPlanUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateUpdatedAt() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionPlanUpsertOne) SetDeletedAt(v time.Time) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateDeletedAt() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubscriptionPlanUpsertOne) ClearDeletedAt() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *SubscriptionPlanUpsertOne) SetName(v string) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateName() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SubscriptionPlanUpsertOne) SetDescription(v string) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateDescription() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SubscriptionPlanUpsertOne) ClearDescription() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.ClearDescription()
	})
}

// SetVisibility sets the "visibility" field.
func (u *SubscriptionPlanUpsertOne) SetVisibility(v string) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateVisibility() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateVisibility()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionPlanUpsertOne) SetStatus(v string) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateStatus() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateStatus()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *SubscriptionPlanUpsertOne) SetDailyLimitUsd(v float64) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *SubscriptionPlanUpsertOne) AddDailyLimitUsd(v float64) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateDailyLimitUsd() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *SubscriptionPlanUpsertOne) ClearDailyLimitUsd() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.ClearDailyLimitUsd()
	})
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *SubscriptionPlanUpsertOne) SetWeeklyLimitUsd(v float64) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetWeeklyLimitUsd(v)
	})
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *SubscriptionPlanUpsertOne) AddWeeklyLimitUsd(v float64) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddWeeklyLimitUsd(v)
	})
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateWeeklyLimitUsd() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateWeeklyLimitUsd()
	})
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (u *SubscriptionPlanUpsertOne) ClearWeeklyLimitUsd() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.ClearWeeklyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *SubscriptionPlanUpsertOne) SetMonthlyLimitUsd(v float64) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *SubscriptionPlanUpsertOne) AddMonthlyLimitUsd(v float64) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateMonthlyLimitUsd() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *SubscriptionPlanUpsertOne) ClearMonthlyLimitUsd() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.ClearMonthlyLimitUsd()
	})
}

// SetDefaultValidityDays sets the "default_validity_days" field.
func (u *SubscriptionPlanUpsertOne) SetDefaultValidityDays(v int) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetDefaultValidityDays(v)
	})
}

// AddDefaultValidityDays adds v to the "default_validity_days" field.
func (u *SubscriptionPlanUpsertOne) AddDefaultValidityDays(v int) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddDefaultValidityDays(v)
	})
}

// UpdateDefaultValidityDays sets the "default_validity_days" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateDefaultValidityDays() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateDefaultValidityDays()
	})
}

// SetPrice sets the "price" field.
func (u *SubscriptionPlanUpsertOne) SetPrice(v float64) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *SubscriptionPlanUpsertOne) AddPrice(v float64) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdatePrice() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdatePrice()
	})
}

// ClearPrice clears the value of the "price" field.
func (u *SubscriptionPlanUpsertOne) ClearPrice() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.ClearPrice()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *SubscriptionPlanUpsertOne) SetSortOrder(v int) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SubscriptionPlanUpsertOne) AddSortOrder(v int) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateSortOrder() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *SubscriptionPlanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionPlanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionPlanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionPlanUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionPlanUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionPlanCreateBulk is the builder for creating many SubscriptionPlan entities in bulk.
type SubscriptionPlanCreateBulk struct {
	config
	err      error
	builders []*SubscriptionPlanCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionPlan entities in the database.
func (_c *SubscriptionPlanCreateBulk) Save(ctx context.Context) ([]*SubscriptionPlan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionPlan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionPlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionPlanCreateBulk) SaveX(ctx context.Context) []*SubscriptionPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionPlan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionPlanUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionPlanCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionPlanUpsertBulk {
	_c.conflict = opts
	return &SubscriptionPlanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionPlanCreateBulk) OnConflictColumns(columns ...string) *SubscriptionPlanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionPlanUpsertBulk{
		create: _c,
	}
}

// SubscriptionPlanUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionPlan nodes.
type SubscriptionPlanUpsertBulk struct {
	create *SubscriptionPlanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionPlanUpsertBulk) UpdateNewValues() *SubscriptionPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionplan.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionPlanUpsertBulk) Ignore() *SubscriptionPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionPlanUpsertBulk) DoNothing() *SubscriptionPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionPlanCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionPlanUpsertBulk) Update(set func(*SubscriptionPlanUpsert)) *SubscriptionPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionPlanUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateUpdatedAt() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionPlanUpsertBulk) SetDeletedAt(v time.Time) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateDeletedAt() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubscriptionPlanUpsertBulk) ClearDeletedAt() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *SubscriptionPlanUpsertBulk) SetName(v string) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateName() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SubscriptionPlanUpsertBulk) SetDescription(v string) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateDescription() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SubscriptionPlanUpsertBulk) ClearDescription() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.ClearDescription()
	})
}

// SetVisibility sets the "visibility" field.
func (u *SubscriptionPlanUpsertBulk) SetVisibility(v string) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateVisibility() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateVisibility()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionPlanUpsertBulk) SetStatus(v string) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateStatus() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateStatus()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *SubscriptionPlanUpsertBulk) SetDailyLimitUsd(v float64) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *SubscriptionPlanUpsertBulk) AddDailyLimitUsd(v float64) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateDailyLimitUsd() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *SubscriptionPlanUpsertBulk) ClearDailyLimitUsd() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.ClearDailyLimitUsd()
	})
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *SubscriptionPlanUpsertBulk) SetWeeklyLimitUsd(v float64) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetWeeklyLimitUsd(v)
	})
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *SubscriptionPlanUpsertBulk) AddWeeklyLimitUsd(v float64) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddWeeklyLimitUsd(v)
	})
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateWeeklyLimitUsd() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateWeeklyLimitUsd()
	})
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (u *SubscriptionPlanUpsertBulk) ClearWeeklyLimitUsd() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.ClearWeeklyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *SubscriptionPlanUpsertBulk) SetMonthlyLimitUsd(v float64) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *SubscriptionPlanUpsertBulk) AddMonthlyLimitUsd(v float64) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateMonthlyLimitUsd() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *SubscriptionPlanUpsertBulk) ClearMonthlyLimitUsd() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.ClearMonthlyLimitUsd()
	})
}

// SetDefaultValidityDays sets the "default_validity_days" field.
func (u *SubscriptionPlanUpsertBulk) SetDefaultValidityDays(v int) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetDefaultValidityDays(v)
	})
}

// AddDefaultValidityDays adds v to the "default_validity_days" field.
func (u *SubscriptionPlanUpsertBulk) AddDefaultValidityDays(v int) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddDefaultValidityDays(v)
	})
}

// UpdateDefaultValidityDays sets the "default_validity_days" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateDefaultValidityDays() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateDefaultValidityDays()
	})
}

// SetPrice sets the "price" field.
func (u *SubscriptionPlanUpsertBulk) SetPrice(v float64) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *SubscriptionPlanUpsertBulk) AddPrice(v float64) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdatePrice() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdatePrice()
	})
}

// ClearPrice clears the value of the "price" field.
func (u *SubscriptionPlanUpsertBulk) ClearPrice() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.ClearPrice()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *SubscriptionPlanUpsertBulk) SetSortOrder(v int) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SubscriptionPlanUpsertBulk) AddSortOrder(v int) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateSortOrder() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *SubscriptionPlanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionPlanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionPlanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionPlanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
