// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/wechatpayorder"
)

// WechatPayOrder is the model entity for the WechatPayOrder schema.
type WechatPayOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// OrderNo holds the value of the "order_no" field.
	OrderNo string `json:"order_no,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// PackageID holds the value of the "package_id" field.
	PackageID int `json:"package_id,omitempty"`
	// CnyFee holds the value of the "cny_fee" field.
	CnyFee int `json:"cny_fee,omitempty"`
	// UsdAmount holds the value of the "usd_amount" field.
	UsdAmount float64 `json:"usd_amount,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// WechatTradeNo holds the value of the "wechat_trade_no" field.
	WechatTradeNo *string `json:"wechat_trade_no,omitempty"`
	// CodeURL holds the value of the "code_url" field.
	CodeURL *string `json:"code_url,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// NotifyData holds the value of the "notify_data" field.
	NotifyData *string `json:"notify_data,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WechatPayOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wechatpayorder.FieldUsdAmount:
			values[i] = new(sql.NullFloat64)
		case wechatpayorder.FieldID, wechatpayorder.FieldUserID, wechatpayorder.FieldPackageID, wechatpayorder.FieldCnyFee:
			values[i] = new(sql.NullInt64)
		case wechatpayorder.FieldOrderNo, wechatpayorder.FieldStatus, wechatpayorder.FieldWechatTradeNo, wechatpayorder.FieldCodeURL, wechatpayorder.FieldNotifyData:
			values[i] = new(sql.NullString)
		case wechatpayorder.FieldExpiresAt, wechatpayorder.FieldPaidAt, wechatpayorder.FieldCreatedAt, wechatpayorder.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WechatPayOrder fields.
func (_m *WechatPayOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wechatpayorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case wechatpayorder.FieldOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_no", values[i])
			} else if value.Valid {
				_m.OrderNo = value.String
			}
		case wechatpayorder.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case wechatpayorder.FieldPackageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field package_id", values[i])
			} else if value.Valid {
				_m.PackageID = int(value.Int64)
			}
		case wechatpayorder.FieldCnyFee:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cny_fee", values[i])
			} else if value.Valid {
				_m.CnyFee = int(value.Int64)
			}
		case wechatpayorder.FieldUsdAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field usd_amount", values[i])
			} else if value.Valid {
				_m.UsdAmount = value.Float64
			}
		case wechatpayorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case wechatpayorder.FieldWechatTradeNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field wechat_trade_no", values[i])
			} else if value.Valid {
				_m.WechatTradeNo = new(string)
				*_m.WechatTradeNo = value.String
			}
		case wechatpayorder.FieldCodeURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_url", values[i])
			} else if value.Valid {
				_m.CodeURL = new(string)
				*_m.CodeURL = value.String
			}
		case wechatpayorder.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case wechatpayorder.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case wechatpayorder.FieldNotifyData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notify_data", values[i])
			} else if value.Valid {
				_m.NotifyData = new(string)
				*_m.NotifyData = value.String
			}
		case wechatpayorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case wechatpayorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WechatPayOrder.
// This includes values selected through modifiers, order, etc.
func (_m *WechatPayOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WechatPayOrder.
// Note that you need to call WechatPayOrder.Unwrap() before calling this method if this WechatPayOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WechatPayOrder) Update() *WechatPayOrderUpdateOne {
	return NewWechatPayOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WechatPayOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WechatPayOrder) Unwrap() *WechatPayOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WechatPayOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WechatPayOrder) String() string {
	var builder strings.Builder
	builder.WriteString("WechatPayOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("order_no=")
	builder.WriteString(_m.OrderNo)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("package_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PackageID))
	builder.WriteString(", ")
	builder.WriteString("cny_fee=")
	builder.WriteString(fmt.Sprintf("%v", _m.CnyFee))
	builder.WriteString(", ")
	builder.WriteString("usd_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsdAmount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.WechatTradeNo; v != nil {
		builder.WriteString("wechat_trade_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CodeURL; v != nil {
		builder.WriteString("code_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NotifyData; v != nil {
		builder.WriteString("notify_data=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WechatPayOrders is a parsable slice of WechatPayOrder.
type WechatPayOrders []*WechatPayOrder
