// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/wechatpayorder"
)

// WechatPayOrderCreate is the builder for creating a WechatPayOrder entity.
type WechatPayOrderCreate struct {
	config
	mutation *WechatPayOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrderNo sets the "order_no" field.
func (_c *WechatPayOrderCreate) SetOrderNo(v string) *WechatPayOrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *WechatPayOrderCreate) SetUserID(v int64) *WechatPayOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPackageID sets the "package_id" field.
func (_c *WechatPayOrderCreate) SetPackageID(v int) *WechatPayOrderCreate {
	_c.mutation.SetPackageID(v)
	return _c
}

// SetCnyFee sets the "cny_fee" field.
func (_c *WechatPayOrderCreate) SetCnyFee(v int) *WechatPayOrderCreate {
	_c.mutation.SetCnyFee(v)
	return _c
}

// SetUsdAmount sets the "usd_amount" field.
func (_c *WechatPayOrderCreate) SetUsdAmount(v float64) *WechatPayOrderCreate {
	_c.mutation.SetUsdAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *WechatPayOrderCreate) SetStatus(v string) *WechatPayOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WechatPayOrderCreate) SetNillableStatus(v *string) *WechatPayOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetWechatTradeNo sets the "wechat_trade_no" field.
func (_c *WechatPayOrderCreate) SetWechatTradeNo(v string) *WechatPayOrderCreate {
	_c.mutation.SetWechatTradeNo(v)
	return _c
}

// SetNillableWechatTradeNo sets the "wechat_trade_no" field if the given value is not nil.
func (_c *WechatPayOrderCreate) SetNillableWechatTradeNo(v *string) *WechatPayOrderCreate {
	if v != nil {
		_c.SetWechatTradeNo(*v)
	}
	return _c
}

// SetCodeURL sets the "code_url" field.
func (_c *WechatPayOrderCreate) SetCodeURL(v string) *WechatPayOrderCreate {
	_c.mutation.SetCodeURL(v)
	return _c
}

// SetNillableCodeURL sets the "code_url" field if the given value is not nil.
func (_c *WechatPayOrderCreate) SetNillableCodeURL(v *string) *WechatPayOrderCreate {
	if v != nil {
		_c.SetCodeURL(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *WechatPayOrderCreate) SetExpiresAt(v time.Time) *WechatPayOrderCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *WechatPayOrderCreate) SetPaidAt(v time.Time) *WechatPayOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *WechatPayOrderCreate) SetNillablePaidAt(v *time.Time) *WechatPayOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetNotifyData sets the "notify_data" field.
func (_c *WechatPayOrderCreate) SetNotifyData(v string) *WechatPayOrderCreate {
	_c.mutation.SetNotifyData(v)
	return _c
}

// SetNillableNotifyData sets the "notify_data" field if the given value is not nil.
func (_c *WechatPayOrderCreate) SetNillableNotifyData(v *string) *WechatPayOrderCreate {
	if v != nil {
		_c.SetNotifyData(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WechatPayOrderCreate) SetCreatedAt(v time.Time) *WechatPayOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WechatPayOrderCreate) SetNillableCreatedAt(v *time.Time) *WechatPayOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WechatPayOrderCreate) SetUpdatedAt(v time.Time) *WechatPayOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WechatPayOrderCreate) SetNillableUpdatedAt(v *time.Time) *WechatPayOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the WechatPayOrderMutation object of the builder.
func (_c *WechatPayOrderCreate) Mutation() *WechatPayOrderMutation {
	return _c.mutation
}

// Save creates the WechatPayOrder in the database.
func (_c *WechatPayOrderCreate) Save(ctx context.Context) (*WechatPayOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WechatPayOrderCreate) SaveX(ctx context.Context) *WechatPayOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WechatPayOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WechatPayOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WechatPayOrderCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := wechatpayorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := wechatpayorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := wechatpayorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WechatPayOrderCreate) check() error {
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "WechatPayOrder.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := wechatpayorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "WechatPayOrder.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "WechatPayOrder.user_id"`)}
	}
	if _, ok := _c.mutation.PackageID(); !ok {
		return &ValidationError{Name: "package_id", err: errors.New(`ent: missing required field "WechatPayOrder.package_id"`)}
	}
	if _, ok := _c.mutation.CnyFee(); !ok {
		return &ValidationError{Name: "cny_fee", err: errors.New(`ent: missing required field "WechatPayOrder.cny_fee"`)}
	}
	if _, ok := _c.mutation.UsdAmount(); !ok {
		return &ValidationError{Name: "usd_amount", err: errors.New(`ent: missing required field "WechatPayOrder.usd_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WechatPayOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := wechatpayorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WechatPayOrder.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.WechatTradeNo(); ok {
		if err := wechatpayorder.WechatTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "wechat_trade_no", err: fmt.Errorf(`ent: validator failed for field "WechatPayOrder.wechat_trade_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "WechatPayOrder.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WechatPayOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WechatPayOrder.updated_at"`)}
	}
	return nil
}

func (_c *WechatPayOrderCreate) sqlSave(ctx context.Context) (*WechatPayOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WechatPayOrderCreate) createSpec() (*WechatPayOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &WechatPayOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wechatpayorder.Table, sqlgraph.NewFieldSpec(wechatpayorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(wechatpayorder.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(wechatpayorder.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.PackageID(); ok {
		_spec.SetField(wechatpayorder.FieldPackageID, field.TypeInt, value)
		_node.PackageID = value
	}
	if value, ok := _c.mutation.CnyFee(); ok {
		_spec.SetField(wechatpayorder.FieldCnyFee, field.TypeInt, value)
		_node.CnyFee = value
	}
	if value, ok := _c.mutation.UsdAmount(); ok {
		_spec.SetField(wechatpayorder.FieldUsdAmount, field.TypeFloat64, value)
		_node.UsdAmount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(wechatpayorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.WechatTradeNo(); ok {
		_spec.SetField(wechatpayorder.FieldWechatTradeNo, field.TypeString, value)
		_node.WechatTradeNo = &value
	}
	if value, ok := _c.mutation.CodeURL(); ok {
		_spec.SetField(wechatpayorder.FieldCodeURL, field.TypeString, value)
		_node.CodeURL = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(wechatpayorder.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(wechatpayorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.NotifyData(); ok {
		_spec.SetField(wechatpayorder.FieldNotifyData, field.TypeString, value)
		_node.NotifyData = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(wechatpayorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(wechatpayorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WechatPayOrder.Create().
//		SetOrderNo(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WechatPayOrderUpsert) {
//			SetOrderNo(v+v).
//		}).
//		Exec(ctx)
func (_c *WechatPayOrderCreate) OnConflict(opts ...sql.ConflictOption) *WechatPayOrderUpsertOne {
	_c.conflict = opts
	return &WechatPayOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WechatPayOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WechatPayOrderCreate) OnConflictColumns(columns ...string) *WechatPayOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WechatPayOrderUpsertOne{
		create: _c,
	}
}

type (
	// WechatPayOrderUpsertOne is the builder for "upsert"-ing
	//  one WechatPayOrder node.
	WechatPayOrderUpsertOne struct {
		create *WechatPayOrderCreate
	}

	// WechatPayOrderUpsert is the "OnConflict" setter.
	WechatPayOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrderNo sets the "order_no" field.
func (u *WechatPayOrderUpsert) SetOrderNo(v string) *WechatPayOrderUpsert {
	u.Set(wechatpayorder.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *WechatPayOrderUpsert) UpdateOrderNo() *WechatPayOrderUpsert {
	u.SetExcluded(wechatpayorder.FieldOrderNo)
	return u
}

// SetUserID sets the "user_id" field.
func (u *WechatPayOrderUpsert) SetUserID(v int64) *WechatPayOrderUpsert {
	u.Set(wechatpayorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WechatPayOrderUpsert) UpdateUserID() *WechatPayOrderUpsert {
	u.SetExcluded(wechatpayorder.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *WechatPayOrderUpsert) AddUserID(v int64) *WechatPayOrderUpsert {
	u.Add(wechatpayorder.FieldUserID, v)
	return u
}

// SetPackageID sets the "package_id" field.
func (u *WechatPayOrderUpsert) SetPackageID(v int) *WechatPayOrderUpsert {
	u.Set(wechatpayorder.FieldPackageID, v)
	return u
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *WechatPayOrderUpsert) UpdatePackageID() *WechatPayOrderUpsert {
	u.SetExcluded(wechatpayorder.FieldPackageID)
	return u
}

// AddPackageID adds v to the "package_id" field.
func (u *WechatPayOrderUpsert) AddPackageID(v int) *WechatPayOrderUpsert {
	u.Add(wechatpayorder.FieldPackageID, v)
	return u
}

// SetCnyFee sets the "cny_fee" field.
func (u *WechatPayOrderUpsert) SetCnyFee(v int) *WechatPayOrderUpsert {
	u.Set(wechatpayorder.FieldCnyFee, v)
	return u
}

// UpdateCnyFee sets the "cny_fee" field to the value that was provided on create.
func (u *WechatPayOrderUpsert) UpdateCnyFee() *WechatPayOrderUpsert {
	u.SetExcluded(wechatpayorder.FieldCnyFee)
	return u
}

// AddCnyFee adds v to the "cny_fee" field.
func (u *WechatPayOrderUpsert) AddCnyFee(v int) *WechatPayOrderUpsert {
	u.Add(wechatpayorder.FieldCnyFee, v)
	return u
}

// SetUsdAmount sets the "usd_amount" field.
func (u *WechatPayOrderUpsert) SetUsdAmount(v float64) *WechatPayOrderUpsert {
	u.Set(wechatpayorder.FieldUsdAmount, v)
	return u
}

// UpdateUsdAmount sets the "usd_amount" field to the value that was provided on create.
func (u *WechatPayOrderUpsert) UpdateUsdAmount() *WechatPayOrderUpsert {
	u.SetExcluded(wechatpayorder.FieldUsdAmount)
	return u
}

// AddUsdAmount adds v to the "usd_amount" field.
func (u *WechatPayOrderUpsert) AddUsdAmount(v float64) *WechatPayOrderUpsert {
	u.Add(wechatpayorder.FieldUsdAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *WechatPayOrderUpsert) SetStatus(v string) *WechatPayOrderUpsert {
	u.Set(wechatpayorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WechatPayOrderUpsert) UpdateStatus() *WechatPayOrderUpsert {
	u.SetExcluded(wechatpayorder.FieldStatus)
	return u
}

// SetWechatTradeNo sets the "wechat_trade_no" field.
func (u *WechatPayOrderUpsert) SetWechatTradeNo(v string) *WechatPayOrderUpsert {
	u.Set(wechatpayorder.FieldWechatTradeNo, v)
	return u
}

// UpdateWechatTradeNo sets the "wechat_trade_no" field to the value that was provided on create.
func (u *WechatPayOrderUpsert) UpdateWechatTradeNo() *WechatPayOrderUpsert {
	u.SetExcluded(wechatpayorder.FieldWechatTradeNo)
	return u
}

// ClearWechatTradeNo clears the value of the "wechat_trade_no" field.
func (u *WechatPayOrderUpsert) ClearWechatTradeNo() *WechatPayOrderUpsert {
	u.SetNull(wechatpayorder.FieldWechatTradeNo)
	return u
}

// SetCodeURL sets the "code_url" field.
func (u *WechatPayOrderUpsert) SetCodeURL(v string) *WechatPayOrderUpsert {
	u.Set(wechatpayorder.FieldCodeURL, v)
	return u
}

// UpdateCodeURL sets the "code_url" field to the value that was provided on create.
func (u *WechatPayOrderUpsert) UpdateCodeURL() *WechatPayOrderUpsert {
	u.SetExcluded(wechatpayorder.FieldCodeURL)
	return u
}

// ClearCodeURL clears the value of the "code_url" field.
func (u *WechatPayOrderUpsert) ClearCodeURL() *WechatPayOrderUpsert {
	u.SetNull(wechatpayorder.FieldCodeURL)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *WechatPayOrderUpsert) SetExpiresAt(v time.Time) *WechatPayOrderUpsert {
	u.Set(wechatpayorder.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *WechatPayOrderUpsert) UpdateExpiresAt() *WechatPayOrderUpsert {
	u.SetExcluded(wechatpayorder.FieldExpiresAt)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *WechatPayOrderUpsert) SetPaidAt(v time.Time) *WechatPayOrderUpsert {
	u.Set(wechatpayorder.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *WechatPayOrderUpsert) UpdatePaidAt() *WechatPayOrderUpsert {
	u.SetExcluded(wechatpayorder.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *WechatPayOrderUpsert) ClearPaidAt() *WechatPayOrderUpsert {
	u.SetNull(wechatpayorder.FieldPaidAt)
	return u
}

// SetNotifyData sets the "notify_data" field.
func (u *WechatPayOrderUpsert) SetNotifyData(v string) *WechatPayOrderUpsert {
	u.Set(wechatpayorder.FieldNotifyData, v)
	return u
}

// UpdateNotifyData sets the "notify_data" field to the value that was provided on create.
func (u *WechatPayOrderUpsert) UpdateNotifyData() *WechatPayOrderUpsert {
	u.SetExcluded(wechatpayorder.FieldNotifyData)
	return u
}

// ClearNotifyData clears the value of the "notify_data" field.
func (u *WechatPayOrderUpsert) ClearNotifyData() *WechatPayOrderUpsert {
	u.SetNull(wechatpayorder.FieldNotifyData)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WechatPayOrderUpsert) SetUpdatedAt(v time.Time) *WechatPayOrderUpsert {
	u.Set(wechatpayorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WechatPayOrderUpsert) UpdateUpdatedAt() *WechatPayOrderUpsert {
	u.SetExcluded(wechatpayorder.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WechatPayOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WechatPayOrderUpsertOne) UpdateNewValues() *WechatPayOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(wechatpayorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WechatPayOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WechatPayOrderUpsertOne) Ignore() *WechatPayOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WechatPayOrderUpsertOne) DoNothing() *WechatPayOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WechatPayOrderCreate.OnConflict
// documentation for more info.
func (u *WechatPayOrderUpsertOne) Update(set func(*WechatPayOrderUpsert)) *WechatPayOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WechatPayOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *WechatPayOrderUpsertOne) SetOrderNo(v string) *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *WechatPayOrderUpsertOne) UpdateOrderNo() *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *WechatPayOrderUpsertOne) SetUserID(v int64) *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *WechatPayOrderUpsertOne) AddUserID(v int64) *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WechatPayOrderUpsertOne) UpdateUserID() *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetPackageID sets the "package_id" field.
func (u *WechatPayOrderUpsertOne) SetPackageID(v int) *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetPackageID(v)
	})
}

// AddPackageID adds v to the "package_id" field.
func (u *WechatPayOrderUpsertOne) AddPackageID(v int) *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.AddPackageID(v)
	})
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *WechatPayOrderUpsertOne) UpdatePackageID() *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdatePackageID()
	})
}

// SetCnyFee sets the "cny_fee" field.
func (u *WechatPayOrderUpsertOne) SetCnyFee(v int) *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetCnyFee(v)
	})
}

// AddCnyFee adds v to the "cny_fee" field.
func (u *WechatPayOrderUpsertOne) AddCnyFee(v int) *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.AddCnyFee(v)
	})
}

// UpdateCnyFee sets the "cny_fee" field to the value that was provided on create.
func (u *WechatPayOrderUpsertOne) UpdateCnyFee() *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateCnyFee()
	})
}

// SetUsdAmount sets the "usd_amount" field.
func (u *WechatPayOrderUpsertOne) SetUsdAmount(v float64) *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetUsdAmount(v)
	})
}

// AddUsdAmount adds v to the "usd_amount" field.
func (u *WechatPayOrderUpsertOne) AddUsdAmount(v float64) *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.AddUsdAmount(v)
	})
}

// UpdateUsdAmount sets the "usd_amount" field to the value that was provided on create.
func (u *WechatPayOrderUpsertOne) UpdateUsdAmount() *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateUsdAmount()
	})
}

// SetStatus sets the "status" field.
func (u *WechatPayOrderUpsertOne) SetStatus(v string) *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WechatPayOrderUpsertOne) UpdateStatus() *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetWechatTradeNo sets the "wechat_trade_no" field.
func (u *WechatPayOrderUpsertOne) SetWechatTradeNo(v string) *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetWechatTradeNo(v)
	})
}

// UpdateWechatTradeNo sets the "wechat_trade_no" field to the value that was provided on create.
func (u *WechatPayOrderUpsertOne) UpdateWechatTradeNo() *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateWechatTradeNo()
	})
}

// ClearWechatTradeNo clears the value of the "wechat_trade_no" field.
func (u *WechatPayOrderUpsertOne) ClearWechatTradeNo() *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.ClearWechatTradeNo()
	})
}

// SetCodeURL sets the "code_url" field.
func (u *WechatPayOrderUpsertOne) SetCodeURL(v string) *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetCodeURL(v)
	})
}

// UpdateCodeURL sets the "code_url" field to the value that was provided on create.
func (u *WechatPayOrderUpsertOne) UpdateCodeURL() *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateCodeURL()
	})
}

// ClearCodeURL clears the value of the "code_url" field.
func (u *WechatPayOrderUpsertOne) ClearCodeURL() *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.ClearCodeURL()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *WechatPayOrderUpsertOne) SetExpiresAt(v time.Time) *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *WechatPayOrderUpsertOne) UpdateExpiresAt() *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *WechatPayOrderUpsertOne) SetPaidAt(v time.Time) *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *WechatPayOrderUpsertOne) UpdatePaidAt() *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *WechatPayOrderUpsertOne) ClearPaidAt() *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetNotifyData sets the "notify_data" field.
func (u *WechatPayOrderUpsertOne) SetNotifyData(v string) *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetNotifyData(v)
	})
}

// UpdateNotifyData sets the "notify_data" field to the value that was provided on create.
func (u *WechatPayOrderUpsertOne) UpdateNotifyData() *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateNotifyData()
	})
}

// ClearNotifyData clears the value of the "notify_data" field.
func (u *WechatPayOrderUpsertOne) ClearNotifyData() *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.ClearNotifyData()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WechatPayOrderUpsertOne) SetUpdatedAt(v time.Time) *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WechatPayOrderUpsertOne) UpdateUpdatedAt() *WechatPayOrderUpsertOne {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WechatPayOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WechatPayOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WechatPayOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WechatPayOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WechatPayOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WechatPayOrderCreateBulk is the builder for creating many WechatPayOrder entities in bulk.
type WechatPayOrderCreateBulk struct {
	config
	err      error
	builders []*WechatPayOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the WechatPayOrder entities in the database.
func (_c *WechatPayOrderCreateBulk) Save(ctx context.Context) ([]*WechatPayOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WechatPayOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WechatPayOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WechatPayOrderCreateBulk) SaveX(ctx context.Context) []*WechatPayOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WechatPayOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WechatPayOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WechatPayOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WechatPayOrderUpsert) {
//			SetOrderNo(v+v).
//		}).
//		Exec(ctx)
func (_c *WechatPayOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *WechatPayOrderUpsertBulk {
	_c.conflict = opts
	return &WechatPayOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WechatPayOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WechatPayOrderCreateBulk) OnConflictColumns(columns ...string) *WechatPayOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WechatPayOrderUpsertBulk{
		create: _c,
	}
}

// WechatPayOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of WechatPayOrder nodes.
type WechatPayOrderUpsertBulk struct {
	create *WechatPayOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WechatPayOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WechatPayOrderUpsertBulk) UpdateNewValues() *WechatPayOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(wechatpayorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WechatPayOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WechatPayOrderUpsertBulk) Ignore() *WechatPayOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WechatPayOrderUpsertBulk) DoNothing() *WechatPayOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WechatPayOrderCreateBulk.OnConflict
// documentation for more info.
func (u *WechatPayOrderUpsertBulk) Update(set func(*WechatPayOrderUpsert)) *WechatPayOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WechatPayOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *WechatPayOrderUpsertBulk) SetOrderNo(v string) *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *WechatPayOrderUpsertBulk) UpdateOrderNo() *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *WechatPayOrderUpsertBulk) SetUserID(v int64) *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *WechatPayOrderUpsertBulk) AddUserID(v int64) *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WechatPayOrderUpsertBulk) UpdateUserID() *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetPackageID sets the "package_id" field.
func (u *WechatPayOrderUpsertBulk) SetPackageID(v int) *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetPackageID(v)
	})
}

// AddPackageID adds v to the "package_id" field.
func (u *WechatPayOrderUpsertBulk) AddPackageID(v int) *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.AddPackageID(v)
	})
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *WechatPayOrderUpsertBulk) UpdatePackageID() *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdatePackageID()
	})
}

// SetCnyFee sets the "cny_fee" field.
func (u *WechatPayOrderUpsertBulk) SetCnyFee(v int) *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetCnyFee(v)
	})
}

// AddCnyFee adds v to the "cny_fee" field.
func (u *WechatPayOrderUpsertBulk) AddCnyFee(v int) *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.AddCnyFee(v)
	})
}

// UpdateCnyFee sets the "cny_fee" field to the value that was provided on create.
func (u *WechatPayOrderUpsertBulk) UpdateCnyFee() *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateCnyFee()
	})
}

// SetUsdAmount sets the "usd_amount" field.
func (u *WechatPayOrderUpsertBulk) SetUsdAmount(v float64) *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetUsdAmount(v)
	})
}

// AddUsdAmount adds v to the "usd_amount" field.
func (u *WechatPayOrderUpsertBulk) AddUsdAmount(v float64) *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.AddUsdAmount(v)
	})
}

// UpdateUsdAmount sets the "usd_amount" field to the value that was provided on create.
func (u *WechatPayOrderUpsertBulk) UpdateUsdAmount() *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateUsdAmount()
	})
}

// SetStatus sets the "status" field.
func (u *WechatPayOrderUpsertBulk) SetStatus(v string) *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WechatPayOrderUpsertBulk) UpdateStatus() *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetWechatTradeNo sets the "wechat_trade_no" field.
func (u *WechatPayOrderUpsertBulk) SetWechatTradeNo(v string) *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetWechatTradeNo(v)
	})
}

// UpdateWechatTradeNo sets the "wechat_trade_no" field to the value that was provided on create.
func (u *WechatPayOrderUpsertBulk) UpdateWechatTradeNo() *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateWechatTradeNo()
	})
}

// ClearWechatTradeNo clears the value of the "wechat_trade_no" field.
func (u *WechatPayOrderUpsertBulk) ClearWechatTradeNo() *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.ClearWechatTradeNo()
	})
}

// SetCodeURL sets the "code_url" field.
func (u *WechatPayOrderUpsertBulk) SetCodeURL(v string) *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetCodeURL(v)
	})
}

// UpdateCodeURL sets the "code_url" field to the value that was provided on create.
func (u *WechatPayOrderUpsertBulk) UpdateCodeURL() *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateCodeURL()
	})
}

// ClearCodeURL clears the value of the "code_url" field.
func (u *WechatPayOrderUpsertBulk) ClearCodeURL() *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.ClearCodeURL()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *WechatPayOrderUpsertBulk) SetExpiresAt(v time.Time) *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *WechatPayOrderUpsertBulk) UpdateExpiresAt() *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *WechatPayOrderUpsertBulk) SetPaidAt(v time.Time) *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *WechatPayOrderUpsertBulk) UpdatePaidAt() *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *WechatPayOrderUpsertBulk) ClearPaidAt() *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetNotifyData sets the "notify_data" field.
func (u *WechatPayOrderUpsertBulk) SetNotifyData(v string) *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetNotifyData(v)
	})
}

// UpdateNotifyData sets the "notify_data" field to the value that was provided on create.
func (u *WechatPayOrderUpsertBulk) UpdateNotifyData() *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateNotifyData()
	})
}

// ClearNotifyData clears the value of the "notify_data" field.
func (u *WechatPayOrderUpsertBulk) ClearNotifyData() *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.ClearNotifyData()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WechatPayOrderUpsertBulk) SetUpdatedAt(v time.Time) *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WechatPayOrderUpsertBulk) UpdateUpdatedAt() *WechatPayOrderUpsertBulk {
	return u.Update(func(s *WechatPayOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WechatPayOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WechatPayOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WechatPayOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WechatPayOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
