// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/wechatpayorder"
)

// WechatPayOrderUpdate is the builder for updating WechatPayOrder entities.
type WechatPayOrderUpdate struct {
	config
	hooks    []Hook
	mutation *WechatPayOrderMutation
}

// Where appends a list predicates to the WechatPayOrderUpdate builder.
func (_u *WechatPayOrderUpdate) Where(ps ...predicate.WechatPayOrder) *WechatPayOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *WechatPayOrderUpdate) SetOrderNo(v string) *WechatPayOrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *WechatPayOrderUpdate) SetNillableOrderNo(v *string) *WechatPayOrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *WechatPayOrderUpdate) SetUserID(v int64) *WechatPayOrderUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WechatPayOrderUpdate) SetNillableUserID(v *int64) *WechatPayOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *WechatPayOrderUpdate) AddUserID(v int64) *WechatPayOrderUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *WechatPayOrderUpdate) SetPackageID(v int) *WechatPayOrderUpdate {
	_u.mutation.ResetPackageID()
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *WechatPayOrderUpdate) SetNillablePackageID(v *int) *WechatPayOrderUpdate {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// AddPackageID adds value to the "package_id" field.
func (_u *WechatPayOrderUpdate) AddPackageID(v int) *WechatPayOrderUpdate {
	_u.mutation.AddPackageID(v)
	return _u
}

// SetCnyFee sets the "cny_fee" field.
func (_u *WechatPayOrderUpdate) SetCnyFee(v int) *WechatPayOrderUpdate {
	_u.mutation.ResetCnyFee()
	_u.mutation.SetCnyFee(v)
	return _u
}

// SetNillableCnyFee sets the "cny_fee" field if the given value is not nil.
func (_u *WechatPayOrderUpdate) SetNillableCnyFee(v *int) *WechatPayOrderUpdate {
	if v != nil {
		_u.SetCnyFee(*v)
	}
	return _u
}

// AddCnyFee adds value to the "cny_fee" field.
func (_u *WechatPayOrderUpdate) AddCnyFee(v int) *WechatPayOrderUpdate {
	_u.mutation.AddCnyFee(v)
	return _u
}

// SetUsdAmount sets the "usd_amount" field.
func (_u *WechatPayOrderUpdate) SetUsdAmount(v float64) *WechatPayOrderUpdate {
	_u.mutation.ResetUsdAmount()
	_u.mutation.SetUsdAmount(v)
	return _u
}

// SetNillableUsdAmount sets the "usd_amount" field if the given value is not nil.
func (_u *WechatPayOrderUpdate) SetNillableUsdAmount(v *float64) *WechatPayOrderUpdate {
	if v != nil {
		_u.SetUsdAmount(*v)
	}
	return _u
}

// AddUsdAmount adds value to the "usd_amount" field.
func (_u *WechatPayOrderUpdate) AddUsdAmount(v float64) *WechatPayOrderUpdate {
	_u.mutation.AddUsdAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *WechatPayOrderUpdate) SetStatus(v string) *WechatPayOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WechatPayOrderUpdate) SetNillableStatus(v *string) *WechatPayOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetWechatTradeNo sets the "wechat_trade_no" field.
func (_u *WechatPayOrderUpdate) SetWechatTradeNo(v string) *WechatPayOrderUpdate {
	_u.mutation.SetWechatTradeNo(v)
	return _u
}

// SetNillableWechatTradeNo sets the "wechat_trade_no" field if the given value is not nil.
func (_u *WechatPayOrderUpdate) SetNillableWechatTradeNo(v *string) *WechatPayOrderUpdate {
	if v != nil {
		_u.SetWechatTradeNo(*v)
	}
	return _u
}

// ClearWechatTradeNo clears the value of the "wechat_trade_no" field.
func (_u *WechatPayOrderUpdate) ClearWechatTradeNo() *WechatPayOrderUpdate {
	_u.mutation.ClearWechatTradeNo()
	return _u
}

// SetCodeURL sets the "code_url" field.
func (_u *WechatPayOrderUpdate) SetCodeURL(v string) *WechatPayOrderUpdate {
	_u.mutation.SetCodeURL(v)
	return _u
}

// SetNillableCodeURL sets the "code_url" field if the given value is not nil.
func (_u *WechatPayOrderUpdate) SetNillableCodeURL(v *string) *WechatPayOrderUpdate {
	if v != nil {
		_u.SetCodeURL(*v)
	}
	return _u
}

// ClearCodeURL clears the value of the "code_url" field.
func (_u *WechatPayOrderUpdate) ClearCodeURL() *WechatPayOrderUpdate {
	_u.mutation.ClearCodeURL()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *WechatPayOrderUpdate) SetExpiresAt(v time.Time) *WechatPayOrderUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *WechatPayOrderUpdate) SetNillableExpiresAt(v *time.Time) *WechatPayOrderUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *WechatPayOrderUpdate) SetPaidAt(v time.Time) *WechatPayOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *WechatPayOrderUpdate) SetNillablePaidAt(v *time.Time) *WechatPayOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *WechatPayOrderUpdate) ClearPaidAt() *WechatPayOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetNotifyData sets the "notify_data" field.
func (_u *WechatPayOrderUpdate) SetNotifyData(v string) *WechatPayOrderUpdate {
	_u.mutation.SetNotifyData(v)
	return _u
}

// SetNillableNotifyData sets the "notify_data" field if the given value is not nil.
func (_u *WechatPayOrderUpdate) SetNillableNotifyData(v *string) *WechatPayOrderUpdate {
	if v != nil {
		_u.SetNotifyData(*v)
	}
	return _u
}

// ClearNotifyData clears the value of the "notify_data" field.
func (_u *WechatPayOrderUpdate) ClearNotifyData() *WechatPayOrderUpdate {
	_u.mutation.ClearNotifyData()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WechatPayOrderUpdate) SetUpdatedAt(v time.Time) *WechatPayOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the WechatPayOrderMutation object of the builder.
func (_u *WechatPayOrderUpdate) Mutation() *WechatPayOrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WechatPayOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WechatPayOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WechatPayOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WechatPayOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WechatPayOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := wechatpayorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WechatPayOrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := wechatpayorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "WechatPayOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := wechatpayorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WechatPayOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WechatTradeNo(); ok {
		if err := wechatpayorder.WechatTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "wechat_trade_no", err: fmt.Errorf(`ent: validator failed for field "WechatPayOrder.wechat_trade_no": %w`, err)}
		}
	}
	return nil
}

func (_u *WechatPayOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wechatpayorder.Table, wechatpayorder.Columns, sqlgraph.NewFieldSpec(wechatpayorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(wechatpayorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(wechatpayorder.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(wechatpayorder.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(wechatpayorder.FieldPackageID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPackageID(); ok {
		_spec.AddField(wechatpayorder.FieldPackageID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CnyFee(); ok {
		_spec.SetField(wechatpayorder.FieldCnyFee, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCnyFee(); ok {
		_spec.AddField(wechatpayorder.FieldCnyFee, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsdAmount(); ok {
		_spec.SetField(wechatpayorder.FieldUsdAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsdAmount(); ok {
		_spec.AddField(wechatpayorder.FieldUsdAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(wechatpayorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.WechatTradeNo(); ok {
		_spec.SetField(wechatpayorder.FieldWechatTradeNo, field.TypeString, value)
	}
	if _u.mutation.WechatTradeNoCleared() {
		_spec.ClearField(wechatpayorder.FieldWechatTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.CodeURL(); ok {
		_spec.SetField(wechatpayorder.FieldCodeURL, field.TypeString, value)
	}
	if _u.mutation.CodeURLCleared() {
		_spec.ClearField(wechatpayorder.FieldCodeURL, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(wechatpayorder.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(wechatpayorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(wechatpayorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NotifyData(); ok {
		_spec.SetField(wechatpayorder.FieldNotifyData, field.TypeString, value)
	}
	if _u.mutation.NotifyDataCleared() {
		_spec.ClearField(wechatpayorder.FieldNotifyData, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(wechatpayorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wechatpayorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WechatPayOrderUpdateOne is the builder for updating a single WechatPayOrder entity.
type WechatPayOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WechatPayOrderMutation
}

// SetOrderNo sets the "order_no" field.
func (_u *WechatPayOrderUpdateOne) SetOrderNo(v string) *WechatPayOrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *WechatPayOrderUpdateOne) SetNillableOrderNo(v *string) *WechatPayOrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *WechatPayOrderUpdateOne) SetUserID(v int64) *WechatPayOrderUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WechatPayOrderUpdateOne) SetNillableUserID(v *int64) *WechatPayOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *WechatPayOrderUpdateOne) AddUserID(v int64) *WechatPayOrderUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *WechatPayOrderUpdateOne) SetPackageID(v int) *WechatPayOrderUpdateOne {
	_u.mutation.ResetPackageID()
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *WechatPayOrderUpdateOne) SetNillablePackageID(v *int) *WechatPayOrderUpdateOne {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// AddPackageID adds value to the "package_id" field.
func (_u *WechatPayOrderUpdateOne) AddPackageID(v int) *WechatPayOrderUpdateOne {
	_u.mutation.AddPackageID(v)
	return _u
}

// SetCnyFee sets the "cny_fee" field.
func (_u *WechatPayOrderUpdateOne) SetCnyFee(v int) *WechatPayOrderUpdateOne {
	_u.mutation.ResetCnyFee()
	_u.mutation.SetCnyFee(v)
	return _u
}

// SetNillableCnyFee sets the "cny_fee" field if the given value is not nil.
func (_u *WechatPayOrderUpdateOne) SetNillableCnyFee(v *int) *WechatPayOrderUpdateOne {
	if v != nil {
		_u.SetCnyFee(*v)
	}
	return _u
}

// AddCnyFee adds value to the "cny_fee" field.
func (_u *WechatPayOrderUpdateOne) AddCnyFee(v int) *WechatPayOrderUpdateOne {
	_u.mutation.AddCnyFee(v)
	return _u
}

// SetUsdAmount sets the "usd_amount" field.
func (_u *WechatPayOrderUpdateOne) SetUsdAmount(v float64) *WechatPayOrderUpdateOne {
	_u.mutation.ResetUsdAmount()
	_u.mutation.SetUsdAmount(v)
	return _u
}

// SetNillableUsdAmount sets the "usd_amount" field if the given value is not nil.
func (_u *WechatPayOrderUpdateOne) SetNillableUsdAmount(v *float64) *WechatPayOrderUpdateOne {
	if v != nil {
		_u.SetUsdAmount(*v)
	}
	return _u
}

// AddUsdAmount adds value to the "usd_amount" field.
func (_u *WechatPayOrderUpdateOne) AddUsdAmount(v float64) *WechatPayOrderUpdateOne {
	_u.mutation.AddUsdAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *WechatPayOrderUpdateOne) SetStatus(v string) *WechatPayOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WechatPayOrderUpdateOne) SetNillableStatus(v *string) *WechatPayOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetWechatTradeNo sets the "wechat_trade_no" field.
func (_u *WechatPayOrderUpdateOne) SetWechatTradeNo(v string) *WechatPayOrderUpdateOne {
	_u.mutation.SetWechatTradeNo(v)
	return _u
}

// SetNillableWechatTradeNo sets the "wechat_trade_no" field if the given value is not nil.
func (_u *WechatPayOrderUpdateOne) SetNillableWechatTradeNo(v *string) *WechatPayOrderUpdateOne {
	if v != nil {
		_u.SetWechatTradeNo(*v)
	}
	return _u
}

// ClearWechatTradeNo clears the value of the "wechat_trade_no" field.
func (_u *WechatPayOrderUpdateOne) ClearWechatTradeNo() *WechatPayOrderUpdateOne {
	_u.mutation.ClearWechatTradeNo()
	return _u
}

// SetCodeURL sets the "code_url" field.
func (_u *WechatPayOrderUpdateOne) SetCodeURL(v string) *WechatPayOrderUpdateOne {
	_u.mutation.SetCodeURL(v)
	return _u
}

// SetNillableCodeURL sets the "code_url" field if the given value is not nil.
func (_u *WechatPayOrderUpdateOne) SetNillableCodeURL(v *string) *WechatPayOrderUpdateOne {
	if v != nil {
		_u.SetCodeURL(*v)
	}
	return _u
}

// ClearCodeURL clears the value of the "code_url" field.
func (_u *WechatPayOrderUpdateOne) ClearCodeURL() *WechatPayOrderUpdateOne {
	_u.mutation.ClearCodeURL()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *WechatPayOrderUpdateOne) SetExpiresAt(v time.Time) *WechatPayOrderUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *WechatPayOrderUpdateOne) SetNillableExpiresAt(v *time.Time) *WechatPayOrderUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *WechatPayOrderUpdateOne) SetPaidAt(v time.Time) *WechatPayOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *WechatPayOrderUpdateOne) SetNillablePaidAt(v *time.Time) *WechatPayOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *WechatPayOrderUpdateOne) ClearPaidAt() *WechatPayOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetNotifyData sets the "notify_data" field.
func (_u *WechatPayOrderUpdateOne) SetNotifyData(v string) *WechatPayOrderUpdateOne {
	_u.mutation.SetNotifyData(v)
	return _u
}

// SetNillableNotifyData sets the "notify_data" field if the given value is not nil.
func (_u *WechatPayOrderUpdateOne) SetNillableNotifyData(v *string) *WechatPayOrderUpdateOne {
	if v != nil {
		_u.SetNotifyData(*v)
	}
	return _u
}

// ClearNotifyData clears the value of the "notify_data" field.
func (_u *WechatPayOrderUpdateOne) ClearNotifyData() *WechatPayOrderUpdateOne {
	_u.mutation.ClearNotifyData()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WechatPayOrderUpdateOne) SetUpdatedAt(v time.Time) *WechatPayOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the WechatPayOrderMutation object of the builder.
func (_u *WechatPayOrderUpdateOne) Mutation() *WechatPayOrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the WechatPayOrderUpdate builder.
func (_u *WechatPayOrderUpdateOne) Where(ps ...predicate.WechatPayOrder) *WechatPayOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WechatPayOrderUpdateOne) Select(field string, fields ...string) *WechatPayOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WechatPayOrder entity.
func (_u *WechatPayOrderUpdateOne) Save(ctx context.Context) (*WechatPayOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WechatPayOrderUpdateOne) SaveX(ctx context.Context) *WechatPayOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WechatPayOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WechatPayOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WechatPayOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := wechatpayorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WechatPayOrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := wechatpayorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "WechatPayOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := wechatpayorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WechatPayOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WechatTradeNo(); ok {
		if err := wechatpayorder.WechatTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "wechat_trade_no", err: fmt.Errorf(`ent: validator failed for field "WechatPayOrder.wechat_trade_no": %w`, err)}
		}
	}
	return nil
}

func (_u *WechatPayOrderUpdateOne) sqlSave(ctx context.Context) (_node *WechatPayOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wechatpayorder.Table, wechatpayorder.Columns, sqlgraph.NewFieldSpec(wechatpayorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WechatPayOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wechatpayorder.FieldID)
		for _, f := range fields {
			if !wechatpayorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wechatpayorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(wechatpayorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(wechatpayorder.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(wechatpayorder.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(wechatpayorder.FieldPackageID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPackageID(); ok {
		_spec.AddField(wechatpayorder.FieldPackageID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CnyFee(); ok {
		_spec.SetField(wechatpayorder.FieldCnyFee, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCnyFee(); ok {
		_spec.AddField(wechatpayorder.FieldCnyFee, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsdAmount(); ok {
		_spec.SetField(wechatpayorder.FieldUsdAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsdAmount(); ok {
		_spec.AddField(wechatpayorder.FieldUsdAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(wechatpayorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.WechatTradeNo(); ok {
		_spec.SetField(wechatpayorder.FieldWechatTradeNo, field.TypeString, value)
	}
	if _u.mutation.WechatTradeNoCleared() {
		_spec.ClearField(wechatpayorder.FieldWechatTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.CodeURL(); ok {
		_spec.SetField(wechatpayorder.FieldCodeURL, field.TypeString, value)
	}
	if _u.mutation.CodeURLCleared() {
		_spec.ClearField(wechatpayorder.FieldCodeURL, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(wechatpayorder.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(wechatpayorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(wechatpayorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NotifyData(); ok {
		_spec.SetField(wechatpayorder.FieldNotifyData, field.TypeString, value)
	}
	if _u.mutation.NotifyDataCleared() {
		_spec.ClearField(wechatpayorder.FieldNotifyData, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(wechatpayorder.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &WechatPayOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wechatpayorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
