// Code generated by ent, DO NOT EDIT.

package wechatpayorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLTE(FieldID, id))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldOrderNo, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldUserID, v))
}

// PackageID applies equality check predicate on the "package_id" field. It's identical to PackageIDEQ.
func PackageID(v int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldPackageID, v))
}

// CnyFee applies equality check predicate on the "cny_fee" field. It's identical to CnyFeeEQ.
func CnyFee(v int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldCnyFee, v))
}

// UsdAmount applies equality check predicate on the "usd_amount" field. It's identical to UsdAmountEQ.
func UsdAmount(v float64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldUsdAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldStatus, v))
}

// WechatTradeNo applies equality check predicate on the "wechat_trade_no" field. It's identical to WechatTradeNoEQ.
func WechatTradeNo(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldWechatTradeNo, v))
}

// CodeURL applies equality check predicate on the "code_url" field. It's identical to CodeURLEQ.
func CodeURL(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldCodeURL, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldExpiresAt, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldPaidAt, v))
}

// NotifyData applies equality check predicate on the "notify_data" field. It's identical to NotifyDataEQ.
func NotifyData(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldNotifyData, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldContainsFold(FieldOrderNo, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLTE(FieldUserID, v))
}

// PackageIDEQ applies the EQ predicate on the "package_id" field.
func PackageIDEQ(v int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldPackageID, v))
}

// PackageIDNEQ applies the NEQ predicate on the "package_id" field.
func PackageIDNEQ(v int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNEQ(FieldPackageID, v))
}

// PackageIDIn applies the In predicate on the "package_id" field.
func PackageIDIn(vs ...int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIn(FieldPackageID, vs...))
}

// PackageIDNotIn applies the NotIn predicate on the "package_id" field.
func PackageIDNotIn(vs ...int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotIn(FieldPackageID, vs...))
}

// PackageIDGT applies the GT predicate on the "package_id" field.
func PackageIDGT(v int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGT(FieldPackageID, v))
}

// PackageIDGTE applies the GTE predicate on the "package_id" field.
func PackageIDGTE(v int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGTE(FieldPackageID, v))
}

// PackageIDLT applies the LT predicate on the "package_id" field.
func PackageIDLT(v int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLT(FieldPackageID, v))
}

// PackageIDLTE applies the LTE predicate on the "package_id" field.
func PackageIDLTE(v int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLTE(FieldPackageID, v))
}

// CnyFeeEQ applies the EQ predicate on the "cny_fee" field.
func CnyFeeEQ(v int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldCnyFee, v))
}

// CnyFeeNEQ applies the NEQ predicate on the "cny_fee" field.
func CnyFeeNEQ(v int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNEQ(FieldCnyFee, v))
}

// CnyFeeIn applies the In predicate on the "cny_fee" field.
func CnyFeeIn(vs ...int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIn(FieldCnyFee, vs...))
}

// CnyFeeNotIn applies the NotIn predicate on the "cny_fee" field.
func CnyFeeNotIn(vs ...int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotIn(FieldCnyFee, vs...))
}

// CnyFeeGT applies the GT predicate on the "cny_fee" field.
func CnyFeeGT(v int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGT(FieldCnyFee, v))
}

// CnyFeeGTE applies the GTE predicate on the "cny_fee" field.
func CnyFeeGTE(v int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGTE(FieldCnyFee, v))
}

// CnyFeeLT applies the LT predicate on the "cny_fee" field.
func CnyFeeLT(v int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLT(FieldCnyFee, v))
}

// CnyFeeLTE applies the LTE predicate on the "cny_fee" field.
func CnyFeeLTE(v int) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLTE(FieldCnyFee, v))
}

// UsdAmountEQ applies the EQ predicate on the "usd_amount" field.
func UsdAmountEQ(v float64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldUsdAmount, v))
}

// UsdAmountNEQ applies the NEQ predicate on the "usd_amount" field.
func UsdAmountNEQ(v float64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNEQ(FieldUsdAmount, v))
}

// UsdAmountIn applies the In predicate on the "usd_amount" field.
func UsdAmountIn(vs ...float64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIn(FieldUsdAmount, vs...))
}

// UsdAmountNotIn applies the NotIn predicate on the "usd_amount" field.
func UsdAmountNotIn(vs ...float64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotIn(FieldUsdAmount, vs...))
}

// UsdAmountGT applies the GT predicate on the "usd_amount" field.
func UsdAmountGT(v float64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGT(FieldUsdAmount, v))
}

// UsdAmountGTE applies the GTE predicate on the "usd_amount" field.
func UsdAmountGTE(v float64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGTE(FieldUsdAmount, v))
}

// UsdAmountLT applies the LT predicate on the "usd_amount" field.
func UsdAmountLT(v float64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLT(FieldUsdAmount, v))
}

// UsdAmountLTE applies the LTE predicate on the "usd_amount" field.
func UsdAmountLTE(v float64) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLTE(FieldUsdAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldContainsFold(FieldStatus, v))
}

// WechatTradeNoEQ applies the EQ predicate on the "wechat_trade_no" field.
func WechatTradeNoEQ(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldWechatTradeNo, v))
}

// WechatTradeNoNEQ applies the NEQ predicate on the "wechat_trade_no" field.
func WechatTradeNoNEQ(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNEQ(FieldWechatTradeNo, v))
}

// WechatTradeNoIn applies the In predicate on the "wechat_trade_no" field.
func WechatTradeNoIn(vs ...string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIn(FieldWechatTradeNo, vs...))
}

// WechatTradeNoNotIn applies the NotIn predicate on the "wechat_trade_no" field.
func WechatTradeNoNotIn(vs ...string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotIn(FieldWechatTradeNo, vs...))
}

// WechatTradeNoGT applies the GT predicate on the "wechat_trade_no" field.
func WechatTradeNoGT(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGT(FieldWechatTradeNo, v))
}

// WechatTradeNoGTE applies the GTE predicate on the "wechat_trade_no" field.
func WechatTradeNoGTE(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGTE(FieldWechatTradeNo, v))
}

// WechatTradeNoLT applies the LT predicate on the "wechat_trade_no" field.
func WechatTradeNoLT(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLT(FieldWechatTradeNo, v))
}

// WechatTradeNoLTE applies the LTE predicate on the "wechat_trade_no" field.
func WechatTradeNoLTE(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLTE(FieldWechatTradeNo, v))
}

// WechatTradeNoContains applies the Contains predicate on the "wechat_trade_no" field.
func WechatTradeNoContains(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldContains(FieldWechatTradeNo, v))
}

// WechatTradeNoHasPrefix applies the HasPrefix predicate on the "wechat_trade_no" field.
func WechatTradeNoHasPrefix(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldHasPrefix(FieldWechatTradeNo, v))
}

// WechatTradeNoHasSuffix applies the HasSuffix predicate on the "wechat_trade_no" field.
func WechatTradeNoHasSuffix(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldHasSuffix(FieldWechatTradeNo, v))
}

// WechatTradeNoIsNil applies the IsNil predicate on the "wechat_trade_no" field.
func WechatTradeNoIsNil() predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIsNull(FieldWechatTradeNo))
}

// WechatTradeNoNotNil applies the NotNil predicate on the "wechat_trade_no" field.
func WechatTradeNoNotNil() predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotNull(FieldWechatTradeNo))
}

// WechatTradeNoEqualFold applies the EqualFold predicate on the "wechat_trade_no" field.
func WechatTradeNoEqualFold(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEqualFold(FieldWechatTradeNo, v))
}

// WechatTradeNoContainsFold applies the ContainsFold predicate on the "wechat_trade_no" field.
func WechatTradeNoContainsFold(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldContainsFold(FieldWechatTradeNo, v))
}

// CodeURLEQ applies the EQ predicate on the "code_url" field.
func CodeURLEQ(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldCodeURL, v))
}

// CodeURLNEQ applies the NEQ predicate on the "code_url" field.
func CodeURLNEQ(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNEQ(FieldCodeURL, v))
}

// CodeURLIn applies the In predicate on the "code_url" field.
func CodeURLIn(vs ...string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIn(FieldCodeURL, vs...))
}

// CodeURLNotIn applies the NotIn predicate on the "code_url" field.
func CodeURLNotIn(vs ...string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotIn(FieldCodeURL, vs...))
}

// CodeURLGT applies the GT predicate on the "code_url" field.
func CodeURLGT(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGT(FieldCodeURL, v))
}

// CodeURLGTE applies the GTE predicate on the "code_url" field.
func CodeURLGTE(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGTE(FieldCodeURL, v))
}

// CodeURLLT applies the LT predicate on the "code_url" field.
func CodeURLLT(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLT(FieldCodeURL, v))
}

// CodeURLLTE applies the LTE predicate on the "code_url" field.
func CodeURLLTE(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLTE(FieldCodeURL, v))
}

// CodeURLContains applies the Contains predicate on the "code_url" field.
func CodeURLContains(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldContains(FieldCodeURL, v))
}

// CodeURLHasPrefix applies the HasPrefix predicate on the "code_url" field.
func CodeURLHasPrefix(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldHasPrefix(FieldCodeURL, v))
}

// CodeURLHasSuffix applies the HasSuffix predicate on the "code_url" field.
func CodeURLHasSuffix(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldHasSuffix(FieldCodeURL, v))
}

// CodeURLIsNil applies the IsNil predicate on the "code_url" field.
func CodeURLIsNil() predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIsNull(FieldCodeURL))
}

// CodeURLNotNil applies the NotNil predicate on the "code_url" field.
func CodeURLNotNil() predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotNull(FieldCodeURL))
}

// CodeURLEqualFold applies the EqualFold predicate on the "code_url" field.
func CodeURLEqualFold(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEqualFold(FieldCodeURL, v))
}

// CodeURLContainsFold applies the ContainsFold predicate on the "code_url" field.
func CodeURLContainsFold(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldContainsFold(FieldCodeURL, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLTE(FieldExpiresAt, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotNull(FieldPaidAt))
}

// NotifyDataEQ applies the EQ predicate on the "notify_data" field.
func NotifyDataEQ(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldNotifyData, v))
}

// NotifyDataNEQ applies the NEQ predicate on the "notify_data" field.
func NotifyDataNEQ(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNEQ(FieldNotifyData, v))
}

// NotifyDataIn applies the In predicate on the "notify_data" field.
func NotifyDataIn(vs ...string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIn(FieldNotifyData, vs...))
}

// NotifyDataNotIn applies the NotIn predicate on the "notify_data" field.
func NotifyDataNotIn(vs ...string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotIn(FieldNotifyData, vs...))
}

// NotifyDataGT applies the GT predicate on the "notify_data" field.
func NotifyDataGT(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGT(FieldNotifyData, v))
}

// NotifyDataGTE applies the GTE predicate on the "notify_data" field.
func NotifyDataGTE(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGTE(FieldNotifyData, v))
}

// NotifyDataLT applies the LT predicate on the "notify_data" field.
func NotifyDataLT(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLT(FieldNotifyData, v))
}

// NotifyDataLTE applies the LTE predicate on the "notify_data" field.
func NotifyDataLTE(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLTE(FieldNotifyData, v))
}

// NotifyDataContains applies the Contains predicate on the "notify_data" field.
func NotifyDataContains(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldContains(FieldNotifyData, v))
}

// NotifyDataHasPrefix applies the HasPrefix predicate on the "notify_data" field.
func NotifyDataHasPrefix(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldHasPrefix(FieldNotifyData, v))
}

// NotifyDataHasSuffix applies the HasSuffix predicate on the "notify_data" field.
func NotifyDataHasSuffix(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldHasSuffix(FieldNotifyData, v))
}

// NotifyDataIsNil applies the IsNil predicate on the "notify_data" field.
func NotifyDataIsNil() predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIsNull(FieldNotifyData))
}

// NotifyDataNotNil applies the NotNil predicate on the "notify_data" field.
func NotifyDataNotNil() predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotNull(FieldNotifyData))
}

// NotifyDataEqualFold applies the EqualFold predicate on the "notify_data" field.
func NotifyDataEqualFold(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEqualFold(FieldNotifyData, v))
}

// NotifyDataContainsFold applies the ContainsFold predicate on the "notify_data" field.
func NotifyDataContainsFold(v string) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldContainsFold(FieldNotifyData, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WechatPayOrder) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WechatPayOrder) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WechatPayOrder) predicate.WechatPayOrder {
	return predicate.WechatPayOrder(sql.NotPredicates(p))
}
