// Code generated by ent, DO NOT EDIT.

package alipayorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLTE(FieldID, id))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldOrderNo, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldUserID, v))
}

// PackageID applies equality check predicate on the "package_id" field. It's identical to PackageIDEQ.
func PackageID(v int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldPackageID, v))
}

// CnyFee applies equality check predicate on the "cny_fee" field. It's identical to CnyFeeEQ.
func CnyFee(v int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldCnyFee, v))
}

// UsdAmount applies equality check predicate on the "usd_amount" field. It's identical to UsdAmountEQ.
func UsdAmount(v float64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldUsdAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldStatus, v))
}

// AlipayTradeNo applies equality check predicate on the "alipay_trade_no" field. It's identical to AlipayTradeNoEQ.
func AlipayTradeNo(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldAlipayTradeNo, v))
}

// QrCode applies equality check predicate on the "qr_code" field. It's identical to QrCodeEQ.
func QrCode(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldQrCode, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldExpiresAt, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldPaidAt, v))
}

// NotifyData applies equality check predicate on the "notify_data" field. It's identical to NotifyDataEQ.
func NotifyData(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldNotifyData, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldContainsFold(FieldOrderNo, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLTE(FieldUserID, v))
}

// PackageIDEQ applies the EQ predicate on the "package_id" field.
func PackageIDEQ(v int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldPackageID, v))
}

// PackageIDNEQ applies the NEQ predicate on the "package_id" field.
func PackageIDNEQ(v int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNEQ(FieldPackageID, v))
}

// PackageIDIn applies the In predicate on the "package_id" field.
func PackageIDIn(vs ...int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIn(FieldPackageID, vs...))
}

// PackageIDNotIn applies the NotIn predicate on the "package_id" field.
func PackageIDNotIn(vs ...int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotIn(FieldPackageID, vs...))
}

// PackageIDGT applies the GT predicate on the "package_id" field.
func PackageIDGT(v int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGT(FieldPackageID, v))
}

// PackageIDGTE applies the GTE predicate on the "package_id" field.
func PackageIDGTE(v int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGTE(FieldPackageID, v))
}

// PackageIDLT applies the LT predicate on the "package_id" field.
func PackageIDLT(v int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLT(FieldPackageID, v))
}

// PackageIDLTE applies the LTE predicate on the "package_id" field.
func PackageIDLTE(v int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLTE(FieldPackageID, v))
}

// CnyFeeEQ applies the EQ predicate on the "cny_fee" field.
func CnyFeeEQ(v int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldCnyFee, v))
}

// CnyFeeNEQ applies the NEQ predicate on the "cny_fee" field.
func CnyFeeNEQ(v int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNEQ(FieldCnyFee, v))
}

// CnyFeeIn applies the In predicate on the "cny_fee" field.
func CnyFeeIn(vs ...int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIn(FieldCnyFee, vs...))
}

// CnyFeeNotIn applies the NotIn predicate on the "cny_fee" field.
func CnyFeeNotIn(vs ...int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotIn(FieldCnyFee, vs...))
}

// CnyFeeGT applies the GT predicate on the "cny_fee" field.
func CnyFeeGT(v int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGT(FieldCnyFee, v))
}

// CnyFeeGTE applies the GTE predicate on the "cny_fee" field.
func CnyFeeGTE(v int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGTE(FieldCnyFee, v))
}

// CnyFeeLT applies the LT predicate on the "cny_fee" field.
func CnyFeeLT(v int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLT(FieldCnyFee, v))
}

// CnyFeeLTE applies the LTE predicate on the "cny_fee" field.
func CnyFeeLTE(v int) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLTE(FieldCnyFee, v))
}

// UsdAmountEQ applies the EQ predicate on the "usd_amount" field.
func UsdAmountEQ(v float64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldUsdAmount, v))
}

// UsdAmountNEQ applies the NEQ predicate on the "usd_amount" field.
func UsdAmountNEQ(v float64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNEQ(FieldUsdAmount, v))
}

// UsdAmountIn applies the In predicate on the "usd_amount" field.
func UsdAmountIn(vs ...float64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIn(FieldUsdAmount, vs...))
}

// UsdAmountNotIn applies the NotIn predicate on the "usd_amount" field.
func UsdAmountNotIn(vs ...float64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotIn(FieldUsdAmount, vs...))
}

// UsdAmountGT applies the GT predicate on the "usd_amount" field.
func UsdAmountGT(v float64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGT(FieldUsdAmount, v))
}

// UsdAmountGTE applies the GTE predicate on the "usd_amount" field.
func UsdAmountGTE(v float64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGTE(FieldUsdAmount, v))
}

// UsdAmountLT applies the LT predicate on the "usd_amount" field.
func UsdAmountLT(v float64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLT(FieldUsdAmount, v))
}

// UsdAmountLTE applies the LTE predicate on the "usd_amount" field.
func UsdAmountLTE(v float64) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLTE(FieldUsdAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldContainsFold(FieldStatus, v))
}

// AlipayTradeNoEQ applies the EQ predicate on the "alipay_trade_no" field.
func AlipayTradeNoEQ(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldAlipayTradeNo, v))
}

// AlipayTradeNoNEQ applies the NEQ predicate on the "alipay_trade_no" field.
func AlipayTradeNoNEQ(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNEQ(FieldAlipayTradeNo, v))
}

// AlipayTradeNoIn applies the In predicate on the "alipay_trade_no" field.
func AlipayTradeNoIn(vs ...string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIn(FieldAlipayTradeNo, vs...))
}

// AlipayTradeNoNotIn applies the NotIn predicate on the "alipay_trade_no" field.
func AlipayTradeNoNotIn(vs ...string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotIn(FieldAlipayTradeNo, vs...))
}

// AlipayTradeNoGT applies the GT predicate on the "alipay_trade_no" field.
func AlipayTradeNoGT(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGT(FieldAlipayTradeNo, v))
}

// AlipayTradeNoGTE applies the GTE predicate on the "alipay_trade_no" field.
func AlipayTradeNoGTE(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGTE(FieldAlipayTradeNo, v))
}

// AlipayTradeNoLT applies the LT predicate on the "alipay_trade_no" field.
func AlipayTradeNoLT(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLT(FieldAlipayTradeNo, v))
}

// AlipayTradeNoLTE applies the LTE predicate on the "alipay_trade_no" field.
func AlipayTradeNoLTE(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLTE(FieldAlipayTradeNo, v))
}

// AlipayTradeNoContains applies the Contains predicate on the "alipay_trade_no" field.
func AlipayTradeNoContains(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldContains(FieldAlipayTradeNo, v))
}

// AlipayTradeNoHasPrefix applies the HasPrefix predicate on the "alipay_trade_no" field.
func AlipayTradeNoHasPrefix(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldHasPrefix(FieldAlipayTradeNo, v))
}

// AlipayTradeNoHasSuffix applies the HasSuffix predicate on the "alipay_trade_no" field.
func AlipayTradeNoHasSuffix(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldHasSuffix(FieldAlipayTradeNo, v))
}

// AlipayTradeNoIsNil applies the IsNil predicate on the "alipay_trade_no" field.
func AlipayTradeNoIsNil() predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIsNull(FieldAlipayTradeNo))
}

// AlipayTradeNoNotNil applies the NotNil predicate on the "alipay_trade_no" field.
func AlipayTradeNoNotNil() predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotNull(FieldAlipayTradeNo))
}

// AlipayTradeNoEqualFold applies the EqualFold predicate on the "alipay_trade_no" field.
func AlipayTradeNoEqualFold(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEqualFold(FieldAlipayTradeNo, v))
}

// AlipayTradeNoContainsFold applies the ContainsFold predicate on the "alipay_trade_no" field.
func AlipayTradeNoContainsFold(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldContainsFold(FieldAlipayTradeNo, v))
}

// QrCodeEQ applies the EQ predicate on the "qr_code" field.
func QrCodeEQ(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldQrCode, v))
}

// QrCodeNEQ applies the NEQ predicate on the "qr_code" field.
func QrCodeNEQ(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNEQ(FieldQrCode, v))
}

// QrCodeIn applies the In predicate on the "qr_code" field.
func QrCodeIn(vs ...string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIn(FieldQrCode, vs...))
}

// QrCodeNotIn applies the NotIn predicate on the "qr_code" field.
func QrCodeNotIn(vs ...string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotIn(FieldQrCode, vs...))
}

// QrCodeGT applies the GT predicate on the "qr_code" field.
func QrCodeGT(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGT(FieldQrCode, v))
}

// QrCodeGTE applies the GTE predicate on the "qr_code" field.
func QrCodeGTE(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGTE(FieldQrCode, v))
}

// QrCodeLT applies the LT predicate on the "qr_code" field.
func QrCodeLT(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLT(FieldQrCode, v))
}

// QrCodeLTE applies the LTE predicate on the "qr_code" field.
func QrCodeLTE(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLTE(FieldQrCode, v))
}

// QrCodeContains applies the Contains predicate on the "qr_code" field.
func QrCodeContains(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldContains(FieldQrCode, v))
}

// QrCodeHasPrefix applies the HasPrefix predicate on the "qr_code" field.
func QrCodeHasPrefix(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldHasPrefix(FieldQrCode, v))
}

// QrCodeHasSuffix applies the HasSuffix predicate on the "qr_code" field.
func QrCodeHasSuffix(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldHasSuffix(FieldQrCode, v))
}

// QrCodeIsNil applies the IsNil predicate on the "qr_code" field.
func QrCodeIsNil() predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIsNull(FieldQrCode))
}

// QrCodeNotNil applies the NotNil predicate on the "qr_code" field.
func QrCodeNotNil() predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotNull(FieldQrCode))
}

// QrCodeEqualFold applies the EqualFold predicate on the "qr_code" field.
func QrCodeEqualFold(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEqualFold(FieldQrCode, v))
}

// QrCodeContainsFold applies the ContainsFold predicate on the "qr_code" field.
func QrCodeContainsFold(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldContainsFold(FieldQrCode, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLTE(FieldExpiresAt, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotNull(FieldPaidAt))
}

// NotifyDataEQ applies the EQ predicate on the "notify_data" field.
func NotifyDataEQ(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldNotifyData, v))
}

// NotifyDataNEQ applies the NEQ predicate on the "notify_data" field.
func NotifyDataNEQ(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNEQ(FieldNotifyData, v))
}

// NotifyDataIn applies the In predicate on the "notify_data" field.
func NotifyDataIn(vs ...string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIn(FieldNotifyData, vs...))
}

// NotifyDataNotIn applies the NotIn predicate on the "notify_data" field.
func NotifyDataNotIn(vs ...string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotIn(FieldNotifyData, vs...))
}

// NotifyDataGT applies the GT predicate on the "notify_data" field.
func NotifyDataGT(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGT(FieldNotifyData, v))
}

// NotifyDataGTE applies the GTE predicate on the "notify_data" field.
func NotifyDataGTE(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGTE(FieldNotifyData, v))
}

// NotifyDataLT applies the LT predicate on the "notify_data" field.
func NotifyDataLT(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLT(FieldNotifyData, v))
}

// NotifyDataLTE applies the LTE predicate on the "notify_data" field.
func NotifyDataLTE(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLTE(FieldNotifyData, v))
}

// NotifyDataContains applies the Contains predicate on the "notify_data" field.
func NotifyDataContains(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldContains(FieldNotifyData, v))
}

// NotifyDataHasPrefix applies the HasPrefix predicate on the "notify_data" field.
func NotifyDataHasPrefix(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldHasPrefix(FieldNotifyData, v))
}

// NotifyDataHasSuffix applies the HasSuffix predicate on the "notify_data" field.
func NotifyDataHasSuffix(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldHasSuffix(FieldNotifyData, v))
}

// NotifyDataIsNil applies the IsNil predicate on the "notify_data" field.
func NotifyDataIsNil() predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIsNull(FieldNotifyData))
}

// NotifyDataNotNil applies the NotNil predicate on the "notify_data" field.
func NotifyDataNotNil() predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotNull(FieldNotifyData))
}

// NotifyDataEqualFold applies the EqualFold predicate on the "notify_data" field.
func NotifyDataEqualFold(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEqualFold(FieldNotifyData, v))
}

// NotifyDataContainsFold applies the ContainsFold predicate on the "notify_data" field.
func NotifyDataContainsFold(v string) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldContainsFold(FieldNotifyData, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AlipayOrder) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AlipayOrder) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AlipayOrder) predicate.AlipayOrder {
	return predicate.AlipayOrder(sql.NotPredicates(p))
}
